// Code generated by protoc-gen-go.
// source: importer.proto
// DO NOT EDIT!

/*
Package dg_proto is a generated protocol buffer package.

It is generated from these files:
	importer.proto
	matrix.proto

It has these top-level messages:
	SensorFilter
	ImporterResult
	Meta
	Image
	Object
	Attribute
	RecResult
*/
package dg_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SensorFilter struct {
	QualityThreshold    float32 `protobuf:"fixed32,1,opt,name=QualityThreshold,json=qualityThreshold" json:"QualityThreshold,omitempty"`
	IsRemoveDuplication bool    `protobuf:"varint,2,opt,name=IsRemoveDuplication,json=isRemoveDuplication" json:"IsRemoveDuplication,omitempty"`
}

func (m *SensorFilter) Reset()                    { *m = SensorFilter{} }
func (m *SensorFilter) String() string            { return proto.CompactTextString(m) }
func (*SensorFilter) ProtoMessage()               {}
func (*SensorFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SensorFilter) GetQualityThreshold() float32 {
	if m != nil {
		return m.QualityThreshold
	}
	return 0
}

func (m *SensorFilter) GetIsRemoveDuplication() bool {
	if m != nil {
		return m.IsRemoveDuplication
	}
	return false
}

type ImporterResult struct {
	RecResult    *RecResult    `protobuf:"bytes,1,opt,name=RecResult,json=recResult" json:"RecResult,omitempty"`
	SensorFilter *SensorFilter `protobuf:"bytes,2,opt,name=SensorFilter,json=sensorFilter" json:"SensorFilter,omitempty"`
}

func (m *ImporterResult) Reset()                    { *m = ImporterResult{} }
func (m *ImporterResult) String() string            { return proto.CompactTextString(m) }
func (*ImporterResult) ProtoMessage()               {}
func (*ImporterResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ImporterResult) GetRecResult() *RecResult {
	if m != nil {
		return m.RecResult
	}
	return nil
}

func (m *ImporterResult) GetSensorFilter() *SensorFilter {
	if m != nil {
		return m.SensorFilter
	}
	return nil
}

func init() {
	proto.RegisterType((*SensorFilter)(nil), "dg.proto.SensorFilter")
	proto.RegisterType((*ImporterResult)(nil), "dg.proto.ImporterResult")
}

func init() { proto.RegisterFile("importer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0xcc, 0x2d, 0xc8,
	0x2f, 0x2a, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0x49, 0x87, 0xb0,
	0xa4, 0x78, 0x72, 0x13, 0x4b, 0x8a, 0x32, 0x2b, 0x20, 0x3c, 0xa5, 0x1c, 0x2e, 0x9e, 0xe0, 0xd4,
	0xbc, 0xe2, 0xfc, 0x22, 0xb7, 0xcc, 0x9c, 0x92, 0xd4, 0x22, 0x21, 0x2d, 0x2e, 0x81, 0xc0, 0xd2,
	0xc4, 0x9c, 0xcc, 0x92, 0xca, 0x90, 0x8c, 0xa2, 0xd4, 0xe2, 0x8c, 0xfc, 0x9c, 0x14, 0x09, 0x46,
	0x05, 0x46, 0x0d, 0xa6, 0x20, 0x81, 0x42, 0x34, 0x71, 0x21, 0x03, 0x2e, 0x61, 0xcf, 0xe2, 0xa0,
	0xd4, 0xdc, 0xfc, 0xb2, 0x54, 0x97, 0xd2, 0x82, 0x9c, 0xcc, 0xe4, 0xc4, 0x92, 0xcc, 0xfc, 0x3c,
	0x09, 0x26, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0xe1, 0x4c, 0x4c, 0x29, 0xa5, 0x7a, 0x2e, 0x3e, 0x4f,
	0xa8, 0xbb, 0x82, 0x52, 0x8b, 0x4b, 0x73, 0x4a, 0x84, 0x0c, 0xb9, 0x38, 0x83, 0x52, 0x93, 0x21,
	0x1c, 0xb0, 0x45, 0xdc, 0x46, 0xc2, 0x7a, 0x30, 0xb7, 0xea, 0xc1, 0xa5, 0x82, 0x38, 0x8b, 0x60,
	0x4c, 0x21, 0x2b, 0x54, 0x27, 0x83, 0xed, 0xe3, 0x36, 0x12, 0x43, 0xe8, 0x42, 0x96, 0x0d, 0xe2,
	0x29, 0x46, 0xe2, 0x25, 0xb1, 0x81, 0x55, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x43, 0x16,
	0xdb, 0xf5, 0x1f, 0x01, 0x00, 0x00,
}
