// Code generated by protoc-gen-go.
// source: common.proto
// DO NOT EDIT!

package dg_model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ObjType int32

const (
	ObjType_OBJ_TYPE_UNKNOWN             ObjType = 0
	ObjType_OBJ_TYPE_CAR                 ObjType = 1
	ObjType_OBJ_TYPE_BICYCLE             ObjType = 2
	ObjType_OBJ_TYPE_TRICYCLE            ObjType = 3
	ObjType_OBJ_TYPE_PEDESTRIAN          ObjType = 4
	ObjType_OBJ_TYPE_FACE                ObjType = 1024
	ObjType_OBJ_TYPE_VEHICLE_VECTOR      ObjType = 2048
	ObjType_OBJ_TYPE_BICYCLE_VECTOR      ObjType = 2049
	ObjType_OBJ_TYPE_TRICYCLE_VECTOR     ObjType = 2050
	ObjType_OBJ_TYPE_PEDESTRIAN_VECTOR   ObjType = 2051
	ObjType_OBJ_TYPE_FACE_VECTOR         ObjType = 3072
	ObjType_OBJ_TYPE_VEHICLE_CUTBOARD    ObjType = 4096
	ObjType_OBJ_TYPE_BICYCLE_CUTBOARD    ObjType = 4097
	ObjType_OBJ_TYPE_TRICYCLE_CUTBOARD   ObjType = 4098
	ObjType_OBJ_TYPE_PEDESTRIAN_CUTBOARD ObjType = 4099
	ObjType_OBJ_TYPE_FACE_CUTBOARD       ObjType = 5120
)

var ObjType_name = map[int32]string{
	0:    "OBJ_TYPE_UNKNOWN",
	1:    "OBJ_TYPE_CAR",
	2:    "OBJ_TYPE_BICYCLE",
	3:    "OBJ_TYPE_TRICYCLE",
	4:    "OBJ_TYPE_PEDESTRIAN",
	1024: "OBJ_TYPE_FACE",
	2048: "OBJ_TYPE_VEHICLE_VECTOR",
	2049: "OBJ_TYPE_BICYCLE_VECTOR",
	2050: "OBJ_TYPE_TRICYCLE_VECTOR",
	2051: "OBJ_TYPE_PEDESTRIAN_VECTOR",
	3072: "OBJ_TYPE_FACE_VECTOR",
	4096: "OBJ_TYPE_VEHICLE_CUTBOARD",
	4097: "OBJ_TYPE_BICYCLE_CUTBOARD",
	4098: "OBJ_TYPE_TRICYCLE_CUTBOARD",
	4099: "OBJ_TYPE_PEDESTRIAN_CUTBOARD",
	5120: "OBJ_TYPE_FACE_CUTBOARD",
}
var ObjType_value = map[string]int32{
	"OBJ_TYPE_UNKNOWN":             0,
	"OBJ_TYPE_CAR":                 1,
	"OBJ_TYPE_BICYCLE":             2,
	"OBJ_TYPE_TRICYCLE":            3,
	"OBJ_TYPE_PEDESTRIAN":          4,
	"OBJ_TYPE_FACE":                1024,
	"OBJ_TYPE_VEHICLE_VECTOR":      2048,
	"OBJ_TYPE_BICYCLE_VECTOR":      2049,
	"OBJ_TYPE_TRICYCLE_VECTOR":     2050,
	"OBJ_TYPE_PEDESTRIAN_VECTOR":   2051,
	"OBJ_TYPE_FACE_VECTOR":         3072,
	"OBJ_TYPE_VEHICLE_CUTBOARD":    4096,
	"OBJ_TYPE_BICYCLE_CUTBOARD":    4097,
	"OBJ_TYPE_TRICYCLE_CUTBOARD":   4098,
	"OBJ_TYPE_PEDESTRIAN_CUTBOARD": 4099,
	"OBJ_TYPE_FACE_CUTBOARD":       5120,
}

func (x ObjType) String() string {
	return proto.EnumName(ObjType_name, int32(x))
}
func (ObjType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type DataFmtType int32

const (
	DataFmtType_UNKNOWNFMT DataFmtType = 0
	DataFmtType_JSON       DataFmtType = 1
	DataFmtType_PROTOBUF   DataFmtType = 2
	DataFmtType_CSV        DataFmtType = 3
	DataFmtType_PDF        DataFmtType = 4
)

var DataFmtType_name = map[int32]string{
	0: "UNKNOWNFMT",
	1: "JSON",
	2: "PROTOBUF",
	3: "CSV",
	4: "PDF",
}
var DataFmtType_value = map[string]int32{
	"UNKNOWNFMT": 0,
	"JSON":       1,
	"PROTOBUF":   2,
	"CSV":        3,
	"PDF":        4,
}

func (x DataFmtType) String() string {
	return proto.EnumName(DataFmtType_name, int32(x))
}
func (DataFmtType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type SexType int32

const (
	SexType_SEX_TYPE_UNKNOWN SexType = 0
	SexType_SEX_TYPE_MALE    SexType = 1
	SexType_SEX_TYPE_FEMALE  SexType = 2
)

var SexType_name = map[int32]string{
	0: "SEX_TYPE_UNKNOWN",
	1: "SEX_TYPE_MALE",
	2: "SEX_TYPE_FEMALE",
}
var SexType_value = map[string]int32{
	"SEX_TYPE_UNKNOWN": 0,
	"SEX_TYPE_MALE":    1,
	"SEX_TYPE_FEMALE":  2,
}

func (x SexType) String() string {
	return proto.EnumName(SexType_name, int32(x))
}
func (SexType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type NationalType int32

const (
	NationalType_NATIONAL_TYPE_UNKNOWN  NationalType = 0
	NationalType_NATIONAL_TYPE_HAN      NationalType = 1
	NationalType_NATIONAL_TYPE_MINORITY NationalType = 2
)

var NationalType_name = map[int32]string{
	0: "NATIONAL_TYPE_UNKNOWN",
	1: "NATIONAL_TYPE_HAN",
	2: "NATIONAL_TYPE_MINORITY",
}
var NationalType_value = map[string]int32{
	"NATIONAL_TYPE_UNKNOWN":  0,
	"NATIONAL_TYPE_HAN":      1,
	"NATIONAL_TYPE_MINORITY": 2,
}

func (x NationalType) String() string {
	return proto.EnumName(NationalType_name, int32(x))
}
func (NationalType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type AgeType int32

const (
	AgeType_AGE_TYPE_UNKNOWN AgeType = 0
	AgeType_AGE_TYPE_LT15    AgeType = 1
	AgeType_AGE_TYPE_1530    AgeType = 2
	AgeType_AGE_TYPE_3050    AgeType = 3
	AgeType_AGE_TYPE_50UP    AgeType = 4
)

var AgeType_name = map[int32]string{
	0: "AGE_TYPE_UNKNOWN",
	1: "AGE_TYPE_LT15",
	2: "AGE_TYPE_1530",
	3: "AGE_TYPE_3050",
	4: "AGE_TYPE_50UP",
}
var AgeType_value = map[string]int32{
	"AGE_TYPE_UNKNOWN": 0,
	"AGE_TYPE_LT15":    1,
	"AGE_TYPE_1530":    2,
	"AGE_TYPE_3050":    3,
	"AGE_TYPE_50UP":    4,
}

func (x AgeType) String() string {
	return proto.EnumName(AgeType_name, int32(x))
}
func (AgeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type NonMotorVehicleGesture int32

const (
	NonMotorVehicleGesture_ATTITUDE_POSITIVE NonMotorVehicleGesture = 0
	NonMotorVehicleGesture_ATTITUDE_RIGHT    NonMotorVehicleGesture = 1
	NonMotorVehicleGesture_ATTITUDE_LEFT     NonMotorVehicleGesture = 2
	NonMotorVehicleGesture_ATTITUDE_BACK     NonMotorVehicleGesture = 3
)

var NonMotorVehicleGesture_name = map[int32]string{
	0: "ATTITUDE_POSITIVE",
	1: "ATTITUDE_RIGHT",
	2: "ATTITUDE_LEFT",
	3: "ATTITUDE_BACK",
}
var NonMotorVehicleGesture_value = map[string]int32{
	"ATTITUDE_POSITIVE": 0,
	"ATTITUDE_RIGHT":    1,
	"ATTITUDE_LEFT":     2,
	"ATTITUDE_BACK":     3,
}

func (x NonMotorVehicleGesture) String() string {
	return proto.EnumName(NonMotorVehicleGesture_name, int32(x))
}
func (NonMotorVehicleGesture) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

type DBType int32

const (
	DBType_KAFKA     DBType = 0
	DBType_POSTGRES  DBType = 1
	DBType_FILEIMAGE DBType = 2
)

var DBType_name = map[int32]string{
	0: "KAFKA",
	1: "POSTGRES",
	2: "FILEIMAGE",
}
var DBType_value = map[string]int32{
	"KAFKA":     0,
	"POSTGRES":  1,
	"FILEIMAGE": 2,
}

func (x DBType) String() string {
	return proto.EnumName(DBType_name, int32(x))
}
func (DBType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

type SrcMetadata struct {
	Timestamp   int64   `protobuf:"varint,1,opt,name=Timestamp,json=timestamp" json:"Timestamp"`
	Duration    int32   `protobuf:"varint,2,opt,name=Duration,json=duration" json:"Duration"`
	SensorId    int32   `protobuf:"varint,3,opt,name=SensorId,json=sensorId" json:"SensorId"`
	SensorName  string  `protobuf:"bytes,4,opt,name=SensorName,json=sensorName" json:"SensorName"`
	SensorUrl   string  `protobuf:"bytes,5,opt,name=SensorUrl,json=sensorUrl" json:"SensorUrl"`
	RepoId      int32   `protobuf:"varint,6,opt,name=RepoId,json=repoId" json:"RepoId"`
	RepoInfo    string  `protobuf:"bytes,7,opt,name=RepoInfo,json=repoInfo" json:"RepoInfo"`
	ObjType     ObjType `protobuf:"varint,8,opt,name=ObjType,json=objType,enum=dg.model.ObjType" json:"ObjType"`
	SensorIdStr string  `protobuf:"bytes,9,opt,name=SensorIdStr,json=sensorIdStr" json:"SensorIdStr"`
}

func (m *SrcMetadata) Reset()                    { *m = SrcMetadata{} }
func (m *SrcMetadata) String() string            { return proto.CompactTextString(m) }
func (*SrcMetadata) ProtoMessage()               {}
func (*SrcMetadata) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type Cutboard struct {
	X          uint32  `protobuf:"varint,1,opt,name=X,json=x" json:"X"`
	Y          uint32  `protobuf:"varint,2,opt,name=Y,json=y" json:"Y"`
	Width      uint32  `protobuf:"varint,3,opt,name=Width,json=width" json:"Width"`
	Height     uint32  `protobuf:"varint,4,opt,name=Height,json=height" json:"Height"`
	ResWidth   uint32  `protobuf:"varint,5,opt,name=ResWidth,json=resWidth" json:"ResWidth"`
	ResHeight  uint32  `protobuf:"varint,6,opt,name=ResHeight,json=resHeight" json:"ResHeight"`
	Confidence float32 `protobuf:"fixed32,7,opt,name=Confidence,json=confidence" json:"Confidence"`
}

func (m *Cutboard) Reset()                    { *m = Cutboard{} }
func (m *Cutboard) String() string            { return proto.CompactTextString(m) }
func (*Cutboard) ProtoMessage()               {}
func (*Cutboard) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type CutboardImage struct {
	Cutboard *Cutboard `protobuf:"bytes,1,opt,name=Cutboard,json=cutboard" json:"Cutboard"`
	Img      *Image    `protobuf:"bytes,2,opt,name=Img,json=img" json:"Img"`
}

func (m *CutboardImage) Reset()                    { *m = CutboardImage{} }
func (m *CutboardImage) String() string            { return proto.CompactTextString(m) }
func (*CutboardImage) ProtoMessage()               {}
func (*CutboardImage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *CutboardImage) GetCutboard() *Cutboard {
	if m != nil {
		return m.Cutboard
	}
	return nil
}

func (m *CutboardImage) GetImg() *Image {
	if m != nil {
		return m.Img
	}
	return nil
}

type Color struct {
	ColorId    int32   `protobuf:"varint,1,opt,name=ColorId,json=colorId" json:"ColorId"`
	Confidence float32 `protobuf:"fixed32,2,opt,name=Confidence,json=confidence" json:"Confidence"`
	ColorName  string  `protobuf:"bytes,3,opt,name=ColorName,json=colorName" json:"ColorName"`
}

func (m *Color) Reset()                    { *m = Color{} }
func (m *Color) String() string            { return proto.CompactTextString(m) }
func (*Color) ProtoMessage()               {}
func (*Color) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type FeatureVector struct {
	Id      int64  `protobuf:"varint,1,opt,name=Id,json=id" json:"Id"`
	Feature string `protobuf:"bytes,2,opt,name=Feature,json=feature" json:"Feature"`
}

func (m *FeatureVector) Reset()                    { *m = FeatureVector{} }
func (m *FeatureVector) String() string            { return proto.CompactTextString(m) }
func (*FeatureVector) ProtoMessage()               {}
func (*FeatureVector) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type NullMessage struct {
}

func (m *NullMessage) Reset()                    { *m = NullMessage{} }
func (m *NullMessage) String() string            { return proto.CompactTextString(m) }
func (*NullMessage) ProtoMessage()               {}
func (*NullMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

type Image struct {
	Id      string `protobuf:"bytes,1,opt,name=Id,json=id" json:"Id"`
	Width   int32  `protobuf:"varint,2,opt,name=Width,json=width" json:"Width"`
	Height  int32  `protobuf:"varint,3,opt,name=Height,json=height" json:"Height"`
	URI     string `protobuf:"bytes,4,opt,name=URI,json=uRI" json:"URI"`
	BinData string `protobuf:"bytes,5,opt,name=BinData,json=binData" json:"BinData"`
}

func (m *Image) Reset()                    { *m = Image{} }
func (m *Image) String() string            { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()               {}
func (*Image) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

type RecFacePose struct {
	Type   int32     `protobuf:"varint,1,opt,name=Type,json=type" json:"Type"`
	Angles []float32 `protobuf:"fixed32,2,rep,packed,name=Angles,json=angles" json:"Angles"`
}

func (m *RecFacePose) Reset()                    { *m = RecFacePose{} }
func (m *RecFacePose) String() string            { return proto.CompactTextString(m) }
func (*RecFacePose) ProtoMessage()               {}
func (*RecFacePose) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

type RecFace struct {
	Id         int64          `protobuf:"varint,1,opt,name=Id,json=id" json:"Id"`
	Img        *CutboardImage `protobuf:"bytes,2,opt,name=Img,json=img" json:"Img"`
	Features   string         `protobuf:"bytes,3,opt,name=Features,json=features" json:"Features"`
	Confidence float32        `protobuf:"fixed32,4,opt,name=Confidence,json=confidence" json:"Confidence"`
	Pose       *RecFacePose   `protobuf:"bytes,5,opt,name=Pose,json=pose" json:"Pose"`
	BlurScore  float32        `protobuf:"fixed32,6,opt,name=BlurScore,json=blurScore" json:"BlurScore"`
	AlignScore float32        `protobuf:"fixed32,7,opt,name=AlignScore,json=alignScore" json:"AlignScore"`
}

func (m *RecFace) Reset()                    { *m = RecFace{} }
func (m *RecFace) String() string            { return proto.CompactTextString(m) }
func (*RecFace) ProtoMessage()               {}
func (*RecFace) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *RecFace) GetImg() *CutboardImage {
	if m != nil {
		return m.Img
	}
	return nil
}

func (m *RecFace) GetPose() *RecFacePose {
	if m != nil {
		return m.Pose
	}
	return nil
}

type NameAndConfidence struct {
	Id         int32   `protobuf:"varint,1,opt,name=Id,json=id" json:"Id"`
	Name       string  `protobuf:"bytes,2,opt,name=Name,json=name" json:"Name"`
	Confidence float32 `protobuf:"fixed32,3,opt,name=Confidence,json=confidence" json:"Confidence"`
}

func (m *NameAndConfidence) Reset()                    { *m = NameAndConfidence{} }
func (m *NameAndConfidence) String() string            { return proto.CompactTextString(m) }
func (*NameAndConfidence) ProtoMessage()               {}
func (*NameAndConfidence) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

type CategoryAndFeature struct {
	Id           int32                `protobuf:"varint,1,opt,name=Id,json=id" json:"Id"`
	CategoryName string               `protobuf:"bytes,2,opt,name=CategoryName,json=categoryName" json:"CategoryName"`
	Items        []*NameAndConfidence `protobuf:"bytes,3,rep,name=Items,json=items" json:"Items"`
}

func (m *CategoryAndFeature) Reset()                    { *m = CategoryAndFeature{} }
func (m *CategoryAndFeature) String() string            { return proto.CompactTextString(m) }
func (*CategoryAndFeature) ProtoMessage()               {}
func (*CategoryAndFeature) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *CategoryAndFeature) GetItems() []*NameAndConfidence {
	if m != nil {
		return m.Items
	}
	return nil
}

type PeopleAttr struct {
	Sex      *NameAndConfidence    `protobuf:"bytes,1,opt,name=Sex,json=sex" json:"Sex"`
	Age      *NameAndConfidence    `protobuf:"bytes,2,opt,name=Age,json=age" json:"Age"`
	National *NameAndConfidence    `protobuf:"bytes,3,opt,name=National,json=national" json:"National"`
	Category []*CategoryAndFeature `protobuf:"bytes,4,rep,name=Category,json=category" json:"Category"`
}

func (m *PeopleAttr) Reset()                    { *m = PeopleAttr{} }
func (m *PeopleAttr) String() string            { return proto.CompactTextString(m) }
func (*PeopleAttr) ProtoMessage()               {}
func (*PeopleAttr) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *PeopleAttr) GetSex() *NameAndConfidence {
	if m != nil {
		return m.Sex
	}
	return nil
}

func (m *PeopleAttr) GetAge() *NameAndConfidence {
	if m != nil {
		return m.Age
	}
	return nil
}

func (m *PeopleAttr) GetNational() *NameAndConfidence {
	if m != nil {
		return m.National
	}
	return nil
}

func (m *PeopleAttr) GetCategory() []*CategoryAndFeature {
	if m != nil {
		return m.Category
	}
	return nil
}

type RecVehicle struct {
	Id              int64             `protobuf:"varint,1,opt,name=Id,json=id" json:"Id"`
	ModelType       *VehicleModelType `protobuf:"bytes,2,opt,name=ModelType,json=modelType" json:"ModelType"`
	Color           *Color            `protobuf:"bytes,3,opt,name=Color,json=color" json:"Color"`
	Plate           *LicensePlate     `protobuf:"bytes,4,opt,name=Plate,json=plate" json:"Plate"`
	Img             *CutboardImage    `protobuf:"bytes,5,opt,name=Img,json=img" json:"Img"`
	Symbols         []*VehicleSymbol  `protobuf:"bytes,6,rep,name=Symbols,json=symbols" json:"Symbols"`
	Features        string            `protobuf:"bytes,7,opt,name=Features,json=features" json:"Features"`
	VehicleType     ObjType           `protobuf:"varint,8,opt,name=VehicleType,json=vehicleType,enum=dg.model.ObjType" json:"VehicleType"`
	VehicleTypeName string            `protobuf:"bytes,9,opt,name=VehicleTypeName,json=vehicleTypeName" json:"VehicleTypeName"`
	Plates          []*LicensePlate   `protobuf:"bytes,10,rep,name=Plates,json=plates" json:"Plates"`
	Passengers      []*Passenger      `protobuf:"bytes,11,rep,name=Passengers,json=passengers" json:"Passengers"`
}

func (m *RecVehicle) Reset()                    { *m = RecVehicle{} }
func (m *RecVehicle) String() string            { return proto.CompactTextString(m) }
func (*RecVehicle) ProtoMessage()               {}
func (*RecVehicle) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *RecVehicle) GetModelType() *VehicleModelType {
	if m != nil {
		return m.ModelType
	}
	return nil
}

func (m *RecVehicle) GetColor() *Color {
	if m != nil {
		return m.Color
	}
	return nil
}

func (m *RecVehicle) GetPlate() *LicensePlate {
	if m != nil {
		return m.Plate
	}
	return nil
}

func (m *RecVehicle) GetImg() *CutboardImage {
	if m != nil {
		return m.Img
	}
	return nil
}

func (m *RecVehicle) GetSymbols() []*VehicleSymbol {
	if m != nil {
		return m.Symbols
	}
	return nil
}

func (m *RecVehicle) GetPlates() []*LicensePlate {
	if m != nil {
		return m.Plates
	}
	return nil
}

func (m *RecVehicle) GetPassengers() []*Passenger {
	if m != nil {
		return m.Passengers
	}
	return nil
}

type RecNonMotorVehicle struct {
	Id                int64                                    `protobuf:"varint,1,opt,name=Id,json=id" json:"Id"`
	NMVehicleType     int64                                    `protobuf:"varint,2,opt,name=NMVehicleType,json=nMVehicleType" json:"NMVehicleType"`
	NMVehicleTypeName string                                   `protobuf:"bytes,3,opt,name=NMVehicleTypeName,json=nMVehicleTypeName" json:"NMVehicleTypeName"`
	Img               *CutboardImage                           `protobuf:"bytes,4,opt,name=Img,json=img" json:"Img"`
	NMVehicleGesture  NonMotorVehicleGesture                   `protobuf:"varint,5,opt,name=NMVehicleGesture,json=nMVehicleGesture,enum=dg.model.NonMotorVehicleGesture" json:"NMVehicleGesture"`
	Passenger         []*RecNonMotorVehicle_NonMotorPedestrian `protobuf:"bytes,6,rep,name=Passenger,json=passenger" json:"Passenger"`
	NMVehicle         []*CategoryAndFeature                    `protobuf:"bytes,7,rep,name=NMVehicle,json=nMVehicle" json:"NMVehicle"`
}

func (m *RecNonMotorVehicle) Reset()                    { *m = RecNonMotorVehicle{} }
func (m *RecNonMotorVehicle) String() string            { return proto.CompactTextString(m) }
func (*RecNonMotorVehicle) ProtoMessage()               {}
func (*RecNonMotorVehicle) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *RecNonMotorVehicle) GetImg() *CutboardImage {
	if m != nil {
		return m.Img
	}
	return nil
}

func (m *RecNonMotorVehicle) GetPassenger() []*RecNonMotorVehicle_NonMotorPedestrian {
	if m != nil {
		return m.Passenger
	}
	return nil
}

func (m *RecNonMotorVehicle) GetNMVehicle() []*CategoryAndFeature {
	if m != nil {
		return m.NMVehicle
	}
	return nil
}

type RecNonMotorVehicle_NonMotorPedestrian struct {
	Id        int64                 `protobuf:"varint,1,opt,name=Id,json=id" json:"Id"`
	Sex       *NameAndConfidence    `protobuf:"bytes,2,opt,name=Sex,json=sex" json:"Sex"`
	Attribute []*CategoryAndFeature `protobuf:"bytes,3,rep,name=Attribute,json=attribute" json:"Attribute"`
}

func (m *RecNonMotorVehicle_NonMotorPedestrian) Reset()         { *m = RecNonMotorVehicle_NonMotorPedestrian{} }
func (m *RecNonMotorVehicle_NonMotorPedestrian) String() string { return proto.CompactTextString(m) }
func (*RecNonMotorVehicle_NonMotorPedestrian) ProtoMessage()    {}
func (*RecNonMotorVehicle_NonMotorPedestrian) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{13, 0}
}

func (m *RecNonMotorVehicle_NonMotorPedestrian) GetSex() *NameAndConfidence {
	if m != nil {
		return m.Sex
	}
	return nil
}

func (m *RecNonMotorVehicle_NonMotorPedestrian) GetAttribute() []*CategoryAndFeature {
	if m != nil {
		return m.Attribute
	}
	return nil
}

type Passenger struct {
	Id            int64          `protobuf:"varint,1,opt,name=Id,json=id" json:"Id"`
	PassengerAttr *PeopleAttr    `protobuf:"bytes,2,opt,name=PassengerAttr,json=passengerAttr" json:"PassengerAttr"`
	Face          *RecFace       `protobuf:"bytes,3,opt,name=Face,json=face" json:"Face"`
	Driver        bool           `protobuf:"varint,4,opt,name=Driver,json=driver" json:"Driver"`
	Img           *CutboardImage `protobuf:"bytes,5,opt,name=Img,json=img" json:"Img"`
}

func (m *Passenger) Reset()                    { *m = Passenger{} }
func (m *Passenger) String() string            { return proto.CompactTextString(m) }
func (*Passenger) ProtoMessage()               {}
func (*Passenger) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *Passenger) GetPassengerAttr() *PeopleAttr {
	if m != nil {
		return m.PassengerAttr
	}
	return nil
}

func (m *Passenger) GetFace() *RecFace {
	if m != nil {
		return m.Face
	}
	return nil
}

func (m *Passenger) GetImg() *CutboardImage {
	if m != nil {
		return m.Img
	}
	return nil
}

type RecPedestrian struct {
	Id         int64          `protobuf:"varint,1,opt,name=Id,json=id" json:"Id"`
	Img        *CutboardImage `protobuf:"bytes,2,opt,name=Img,json=img" json:"Img"`
	Confidence float32        `protobuf:"fixed32,3,opt,name=Confidence,json=confidence" json:"Confidence"`
	PedesAttr  *PeopleAttr    `protobuf:"bytes,4,opt,name=PedesAttr,json=pedesAttr" json:"PedesAttr"`
	Face       *RecFace       `protobuf:"bytes,5,opt,name=Face,json=face" json:"Face"`
}

func (m *RecPedestrian) Reset()                    { *m = RecPedestrian{} }
func (m *RecPedestrian) String() string            { return proto.CompactTextString(m) }
func (*RecPedestrian) ProtoMessage()               {}
func (*RecPedestrian) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *RecPedestrian) GetImg() *CutboardImage {
	if m != nil {
		return m.Img
	}
	return nil
}

func (m *RecPedestrian) GetPedesAttr() *PeopleAttr {
	if m != nil {
		return m.PedesAttr
	}
	return nil
}

func (m *RecPedestrian) GetFace() *RecFace {
	if m != nil {
		return m.Face
	}
	return nil
}

type VehicleModelType struct {
	Id          int64   `protobuf:"varint,1,opt,name=Id,json=id" json:"Id"`
	BrandId     int32   `protobuf:"varint,2,opt,name=BrandId,json=brandId" json:"BrandId"`
	SubBrandId  int32   `protobuf:"varint,3,opt,name=SubBrandId,json=subBrandId" json:"SubBrandId"`
	ModelYearId int32   `protobuf:"varint,4,opt,name=ModelYearId,json=modelYearId" json:"ModelYearId"`
	Confidence  float32 `protobuf:"fixed32,5,opt,name=Confidence,json=confidence" json:"Confidence"`
	Type        string  `protobuf:"bytes,6,opt,name=Type,json=type" json:"Type"`
	Brand       string  `protobuf:"bytes,7,opt,name=Brand,json=brand" json:"Brand"`
	SubBrand    string  `protobuf:"bytes,8,opt,name=SubBrand,json=subBrand" json:"SubBrand"`
	ModelYear   string  `protobuf:"bytes,9,opt,name=ModelYear,json=modelYear" json:"ModelYear"`
	TypeId      int32   `protobuf:"varint,10,opt,name=TypeId,json=typeId" json:"TypeId"`
	Model       string  `protobuf:"bytes,11,opt,name=Model,json=model" json:"Model"`
	IsHead      int32   `protobuf:"varint,12,opt,name=IsHead,json=isHead" json:"IsHead"`
}

func (m *VehicleModelType) Reset()                    { *m = VehicleModelType{} }
func (m *VehicleModelType) String() string            { return proto.CompactTextString(m) }
func (*VehicleModelType) ProtoMessage()               {}
func (*VehicleModelType) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

type LicensePlate struct {
	PlateText               string    `protobuf:"bytes,1,opt,name=PlateText,json=plateText" json:"PlateText"`
	Color                   *Color    `protobuf:"bytes,2,opt,name=Color,json=color" json:"Color"`
	TypeId                  int32     `protobuf:"varint,3,opt,name=TypeId,json=typeId" json:"TypeId"`
	TypeName                string    `protobuf:"bytes,4,opt,name=TypeName,json=typeName" json:"TypeName"`
	Confidence              float32   `protobuf:"fixed32,5,opt,name=Confidence,json=confidence" json:"Confidence"`
	Cutboard                *Cutboard `protobuf:"bytes,6,opt,name=Cutboard,json=cutboard" json:"Cutboard"`
	LocalProvinceConfidence float32   `protobuf:"fixed32,7,opt,name=LocalProvinceConfidence,json=localProvinceConfidence" json:"LocalProvinceConfidence"`
}

func (m *LicensePlate) Reset()                    { *m = LicensePlate{} }
func (m *LicensePlate) String() string            { return proto.CompactTextString(m) }
func (*LicensePlate) ProtoMessage()               {}
func (*LicensePlate) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *LicensePlate) GetColor() *Color {
	if m != nil {
		return m.Color
	}
	return nil
}

func (m *LicensePlate) GetCutboard() *Cutboard {
	if m != nil {
		return m.Cutboard
	}
	return nil
}

type VehicleSymbol struct {
	SymbolId   int32     `protobuf:"varint,1,opt,name=SymbolId,json=symbolId" json:"SymbolId"`
	SymbolName string    `protobuf:"bytes,2,opt,name=SymbolName,json=symbolName" json:"SymbolName"`
	Symbols    []*Symbol `protobuf:"bytes,3,rep,name=Symbols,json=symbols" json:"Symbols"`
}

func (m *VehicleSymbol) Reset()                    { *m = VehicleSymbol{} }
func (m *VehicleSymbol) String() string            { return proto.CompactTextString(m) }
func (*VehicleSymbol) ProtoMessage()               {}
func (*VehicleSymbol) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

func (m *VehicleSymbol) GetSymbols() []*Symbol {
	if m != nil {
		return m.Symbols
	}
	return nil
}

type Symbol struct {
	Cutboard   *Cutboard `protobuf:"bytes,1,opt,name=Cutboard,json=cutboard" json:"Cutboard"`
	Confidence float32   `protobuf:"fixed32,2,opt,name=Confidence,json=confidence" json:"Confidence"`
}

func (m *Symbol) Reset()                    { *m = Symbol{} }
func (m *Symbol) String() string            { return proto.CompactTextString(m) }
func (*Symbol) ProtoMessage()               {}
func (*Symbol) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

func (m *Symbol) GetCutboard() *Cutboard {
	if m != nil {
		return m.Cutboard
	}
	return nil
}

type StorageConfig struct {
	Address string   `protobuf:"bytes,1,opt,name=Address,json=address" json:"Address"`
	Type    DBType   `protobuf:"varint,2,opt,name=Type,json=type,enum=dg.model.DBType" json:"Type"`
	Tags    []string `protobuf:"bytes,3,rep,name=Tags,json=tags" json:"Tags"`
}

func (m *StorageConfig) Reset()                    { *m = StorageConfig{} }
func (m *StorageConfig) String() string            { return proto.CompactTextString(m) }
func (*StorageConfig) ProtoMessage()               {}
func (*StorageConfig) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

type VehicleObj struct {
	Metadata *SrcMetadata  `protobuf:"bytes,1,opt,name=Metadata,json=metadata" json:"Metadata"`
	Img      *Image        `protobuf:"bytes,2,opt,name=Img,json=img" json:"Img"`
	Vehicle  []*RecVehicle `protobuf:"bytes,3,rep,name=Vehicle,json=vehicle" json:"Vehicle"`
}

func (m *VehicleObj) Reset()                    { *m = VehicleObj{} }
func (m *VehicleObj) String() string            { return proto.CompactTextString(m) }
func (*VehicleObj) ProtoMessage()               {}
func (*VehicleObj) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{21} }

func (m *VehicleObj) GetMetadata() *SrcMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *VehicleObj) GetImg() *Image {
	if m != nil {
		return m.Img
	}
	return nil
}

func (m *VehicleObj) GetVehicle() []*RecVehicle {
	if m != nil {
		return m.Vehicle
	}
	return nil
}

type PedestrianObj struct {
	Metadata   *SrcMetadata     `protobuf:"bytes,1,opt,name=Metadata,json=metadata" json:"Metadata"`
	Img        *Image           `protobuf:"bytes,2,opt,name=Img,json=img" json:"Img"`
	Pedestrian []*RecPedestrian `protobuf:"bytes,3,rep,name=Pedestrian,json=pedestrian" json:"Pedestrian"`
}

func (m *PedestrianObj) Reset()                    { *m = PedestrianObj{} }
func (m *PedestrianObj) String() string            { return proto.CompactTextString(m) }
func (*PedestrianObj) ProtoMessage()               {}
func (*PedestrianObj) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{22} }

func (m *PedestrianObj) GetMetadata() *SrcMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *PedestrianObj) GetImg() *Image {
	if m != nil {
		return m.Img
	}
	return nil
}

func (m *PedestrianObj) GetPedestrian() []*RecPedestrian {
	if m != nil {
		return m.Pedestrian
	}
	return nil
}

func init() {
	proto.RegisterType((*SrcMetadata)(nil), "dg.model.SrcMetadata")
	proto.RegisterType((*Cutboard)(nil), "dg.model.Cutboard")
	proto.RegisterType((*CutboardImage)(nil), "dg.model.CutboardImage")
	proto.RegisterType((*Color)(nil), "dg.model.Color")
	proto.RegisterType((*FeatureVector)(nil), "dg.model.FeatureVector")
	proto.RegisterType((*NullMessage)(nil), "dg.model.NullMessage")
	proto.RegisterType((*Image)(nil), "dg.model.Image")
	proto.RegisterType((*RecFacePose)(nil), "dg.model.RecFacePose")
	proto.RegisterType((*RecFace)(nil), "dg.model.RecFace")
	proto.RegisterType((*NameAndConfidence)(nil), "dg.model.NameAndConfidence")
	proto.RegisterType((*CategoryAndFeature)(nil), "dg.model.CategoryAndFeature")
	proto.RegisterType((*PeopleAttr)(nil), "dg.model.PeopleAttr")
	proto.RegisterType((*RecVehicle)(nil), "dg.model.RecVehicle")
	proto.RegisterType((*RecNonMotorVehicle)(nil), "dg.model.RecNonMotorVehicle")
	proto.RegisterType((*RecNonMotorVehicle_NonMotorPedestrian)(nil), "dg.model.RecNonMotorVehicle.NonMotorPedestrian")
	proto.RegisterType((*Passenger)(nil), "dg.model.Passenger")
	proto.RegisterType((*RecPedestrian)(nil), "dg.model.RecPedestrian")
	proto.RegisterType((*VehicleModelType)(nil), "dg.model.VehicleModelType")
	proto.RegisterType((*LicensePlate)(nil), "dg.model.LicensePlate")
	proto.RegisterType((*VehicleSymbol)(nil), "dg.model.VehicleSymbol")
	proto.RegisterType((*Symbol)(nil), "dg.model.Symbol")
	proto.RegisterType((*StorageConfig)(nil), "dg.model.StorageConfig")
	proto.RegisterType((*VehicleObj)(nil), "dg.model.VehicleObj")
	proto.RegisterType((*PedestrianObj)(nil), "dg.model.PedestrianObj")
	proto.RegisterEnum("dg.model.ObjType", ObjType_name, ObjType_value)
	proto.RegisterEnum("dg.model.DataFmtType", DataFmtType_name, DataFmtType_value)
	proto.RegisterEnum("dg.model.SexType", SexType_name, SexType_value)
	proto.RegisterEnum("dg.model.NationalType", NationalType_name, NationalType_value)
	proto.RegisterEnum("dg.model.AgeType", AgeType_name, AgeType_value)
	proto.RegisterEnum("dg.model.NonMotorVehicleGesture", NonMotorVehicleGesture_name, NonMotorVehicleGesture_value)
	proto.RegisterEnum("dg.model.DBType", DBType_name, DBType_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1989 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x58, 0x5f, 0x6f, 0xdb, 0xc8,
	0x11, 0xaf, 0x44, 0x51, 0x12, 0x47, 0x56, 0x42, 0x6f, 0xfe, 0x58, 0xf1, 0xa5, 0xad, 0x4b, 0xb4,
	0x40, 0xce, 0x6d, 0x5d, 0xc7, 0x41, 0x70, 0xe9, 0xbd, 0xd1, 0xb2, 0xe4, 0xf0, 0x62, 0xfd, 0xc1,
	0x8a, 0x76, 0x62, 0xa0, 0x40, 0x40, 0x49, 0x8c, 0xc2, 0x56, 0x22, 0x55, 0x92, 0xce, 0x25, 0xe8,
	0x4b, 0xee, 0xee, 0xbd, 0x45, 0xfb, 0x01, 0xfa, 0xd4, 0xe7, 0x7e, 0x87, 0xa2, 0x28, 0xd0, 0x2f,
	0xd1, 0x0f, 0x70, 0xdf, 0xa2, 0xb3, 0xcb, 0xe5, 0x92, 0x94, 0x1c, 0x3b, 0x79, 0xb8, 0x27, 0x6b,
	0x67, 0x66, 0x67, 0x7e, 0xf3, 0x67, 0x67, 0x86, 0x86, 0x8d, 0x49, 0xb0, 0x58, 0x04, 0xfe, 0xde,
	0x32, 0x0c, 0xe2, 0x80, 0xd4, 0xa7, 0xb3, 0xbd, 0x45, 0x30, 0x75, 0xe7, 0xc6, 0x3f, 0xca, 0xd0,
	0x18, 0x85, 0x93, 0x9e, 0x1b, 0x3b, 0x53, 0x27, 0x76, 0xc8, 0x7d, 0xd0, 0x6c, 0x6f, 0xe1, 0x46,
	0xb1, 0xb3, 0x58, 0xb6, 0x4a, 0x3b, 0xa5, 0x07, 0x0a, 0xd5, 0xe2, 0x94, 0x40, 0xb6, 0xa1, 0x7e,
	0x74, 0x11, 0x3a, 0xb1, 0x17, 0xf8, 0xad, 0x32, 0x32, 0x55, 0x5a, 0x9f, 0x8a, 0x33, 0xe3, 0x8d,
	0x5c, 0x3f, 0x0a, 0x42, 0x6b, 0xda, 0x52, 0x12, 0x5e, 0x24, 0xce, 0xe4, 0x27, 0x00, 0x09, 0xaf,
	0xef, 0x2c, 0xdc, 0x56, 0x05, 0xb9, 0x1a, 0x85, 0x48, 0x52, 0x98, 0xd5, 0x84, 0x7f, 0x1a, 0xce,
	0x5b, 0x2a, 0x67, 0x6b, 0x51, 0x4a, 0x20, 0x77, 0xa1, 0x4a, 0xdd, 0x65, 0x80, 0x7a, 0xab, 0x5c,
	0x6f, 0x35, 0xe4, 0x27, 0x66, 0x91, 0xd3, 0xfd, 0x57, 0x41, 0xab, 0xc6, 0x2f, 0xd5, 0x43, 0x71,
	0x26, 0xbf, 0x84, 0xda, 0x60, 0xfc, 0x7b, 0xfb, 0xdd, 0xd2, 0x6d, 0xd5, 0x91, 0x75, 0xe3, 0x60,
	0x73, 0x2f, 0xf5, 0x79, 0x4f, 0x30, 0x68, 0x2d, 0x48, 0x7e, 0x90, 0x1d, 0x8c, 0x81, 0x80, 0x3a,
	0x8a, 0xc3, 0x96, 0xc6, 0x75, 0x35, 0xa2, 0x8c, 0x64, 0xfc, 0xb3, 0x04, 0xf5, 0xf6, 0x45, 0x3c,
	0x0e, 0x9c, 0x70, 0x4a, 0x36, 0xa0, 0xf4, 0x82, 0xc7, 0xa6, 0x49, 0x4b, 0x6f, 0xd9, 0xe9, 0x9c,
	0x07, 0x03, 0x4f, 0xef, 0xc8, 0x6d, 0x50, 0x9f, 0x7b, 0xd3, 0xf8, 0x35, 0x0f, 0x41, 0x93, 0xaa,
	0x5f, 0xb3, 0x03, 0xf3, 0xe0, 0xa9, 0xeb, 0xcd, 0x5e, 0xc7, 0xdc, 0xf7, 0x26, 0xad, 0xbe, 0xe6,
	0xa7, 0xc4, 0x83, 0x28, 0xb9, 0xa0, 0x72, 0x0e, 0x7a, 0x90, 0x9c, 0x59, 0x4c, 0x90, 0x27, 0xae,
	0x55, 0x39, 0x53, 0x0b, 0x53, 0x02, 0x8b, 0x68, 0x3b, 0xf0, 0x5f, 0x79, 0x53, 0xd7, 0x9f, 0xb8,
	0xdc, 0xfb, 0x32, 0x85, 0x89, 0xa4, 0x18, 0x63, 0x68, 0xa6, 0x78, 0xad, 0x85, 0x33, 0x73, 0xc9,
	0x5e, 0xe6, 0x00, 0xc7, 0xde, 0x38, 0x20, 0x59, 0x44, 0x52, 0x0e, 0xad, 0x4f, 0x52, 0x27, 0x7f,
	0x06, 0x8a, 0xb5, 0x98, 0x71, 0xc7, 0x1a, 0x07, 0x37, 0x33, 0x51, 0xae, 0x8d, 0x2a, 0xde, 0x62,
	0x66, 0xbc, 0x04, 0xb5, 0x1d, 0xcc, 0x83, 0x90, 0xb4, 0xa0, 0xc6, 0x7f, 0x58, 0x89, 0x6a, 0x95,
	0xd6, 0x26, 0xc9, 0x71, 0x05, 0x66, 0x79, 0x15, 0x26, 0x73, 0x92, 0xdf, 0xe4, 0x75, 0xa1, 0x24,
	0x89, 0x9f, 0xa4, 0x04, 0xe3, 0xb7, 0xd0, 0xec, 0xba, 0x4e, 0x7c, 0x11, 0xba, 0x67, 0xee, 0x24,
	0x46, 0x43, 0x37, 0xa0, 0x2c, 0x6c, 0x28, 0xb4, 0xec, 0x4d, 0x99, 0x61, 0x21, 0xc0, 0x75, 0x6b,
	0xb4, 0xf6, 0x2a, 0x39, 0x1a, 0x4d, 0x68, 0xf4, 0x2f, 0xe6, 0xf3, 0x9e, 0x1b, 0x45, 0x88, 0xd7,
	0xf8, 0x23, 0xa8, 0x49, 0x18, 0x32, 0x0d, 0x1a, 0xd7, 0x20, 0xf3, 0x95, 0x94, 0xf3, 0x5a, 0xbe,
	0x92, 0x4a, 0x4e, 0xf3, 0xa5, 0x83, 0x72, 0x4a, 0x2d, 0x51, 0xc0, 0xca, 0x05, 0xb5, 0x18, 0x82,
	0x43, 0xcf, 0x3f, 0xc2, 0xa7, 0x23, 0xea, 0xb6, 0x36, 0x4e, 0x8e, 0x08, 0xbe, 0x41, 0xdd, 0x49,
	0xd7, 0x99, 0xb8, 0xc3, 0x20, 0x72, 0x09, 0x81, 0x0a, 0xaf, 0xc6, 0x24, 0x40, 0x95, 0x98, 0xd5,
	0x1d, 0x9a, 0x31, 0xfd, 0xd9, 0xdc, 0x8d, 0xd0, 0xba, 0x82, 0x91, 0xa9, 0x3a, 0xfc, 0x64, 0x7c,
	0x5f, 0x82, 0x9a, 0xb8, 0xbb, 0xe6, 0xf2, 0xe7, 0xf9, 0xbc, 0x6c, 0xad, 0xa7, 0x30, 0xcb, 0x0f,
	0xab, 0x2e, 0x11, 0x9d, 0x48, 0xc4, 0xb6, 0x2e, 0xc2, 0x13, 0xad, 0x24, 0xa6, 0xb2, 0x96, 0x98,
	0xcf, 0xa1, 0xc2, 0x60, 0x73, 0xa7, 0x1a, 0x07, 0x77, 0x32, 0x3b, 0x39, 0x9f, 0x68, 0x65, 0xc9,
	0x3c, 0xc3, 0x1c, 0x1e, 0xce, 0x2f, 0xc2, 0xd1, 0x24, 0xc0, 0x34, 0x54, 0xb9, 0x26, 0x6d, 0x9c,
	0x12, 0x98, 0x21, 0x73, 0xee, 0xcd, 0xfc, 0x84, 0x2d, 0x0a, 0xd5, 0x91, 0x14, 0xe3, 0x39, 0x6c,
	0xb2, 0x5c, 0x9b, 0xfe, 0x34, 0xc3, 0x93, 0x73, 0x5a, 0xe5, 0x4e, 0x63, 0xf0, 0x78, 0x85, 0x24,
	0x49, 0xae, 0xf8, 0xac, 0x67, 0x14, 0x3d, 0x50, 0xd6, 0x5e, 0xc0, 0x9f, 0x80, 0xb4, 0x9d, 0xd8,
	0x9d, 0x05, 0xe1, 0x3b, 0x54, 0x2e, 0x02, 0xb1, 0xa6, 0xd9, 0x80, 0x8d, 0x54, 0x2a, 0x67, 0x61,
	0x63, 0x92, 0xa3, 0x91, 0x87, 0x58, 0x3c, 0xb1, 0xbb, 0x60, 0x41, 0x54, 0x30, 0x18, 0x9f, 0x65,
	0xc1, 0x58, 0x43, 0x4e, 0x55, 0x8f, 0x49, 0x1a, 0xff, 0x2b, 0x01, 0x0c, 0xdd, 0x60, 0x39, 0x77,
	0xcd, 0x38, 0x0e, 0xc9, 0xaf, 0x41, 0x19, 0xb9, 0x6f, 0xc5, 0xbb, 0xbb, 0xf2, 0xbe, 0x12, 0xb9,
	0x6f, 0x99, 0xb8, 0x39, 0x73, 0x45, 0x8e, 0xaf, 0x16, 0x67, 0x35, 0xfd, 0x05, 0xd4, 0xfb, 0xbc,
	0x07, 0x3b, 0x73, 0x1e, 0x87, 0x6b, 0xee, 0xd4, 0x7d, 0x21, 0x4c, 0x9e, 0x60, 0x4f, 0x10, 0x8e,
	0x62, 0x09, 0x30, 0xdf, 0xee, 0xe7, 0x0a, 0x6a, 0x2d, 0x78, 0xd8, 0x1d, 0x04, 0xcd, 0xf8, 0x5e,
	0x01, 0xc0, 0x4a, 0x38, 0x73, 0x5f, 0x7b, 0x93, 0xf9, 0x7a, 0x91, 0x3e, 0x01, 0xad, 0xc7, 0x94,
	0xf0, 0x8a, 0x4f, 0xdc, 0xd8, 0xce, 0x34, 0x8b, 0x5b, 0x52, 0x82, 0x6a, 0x8b, 0xf4, 0x27, 0xf9,
	0x85, 0xe8, 0x29, 0xc2, 0x91, 0x5c, 0xe3, 0xe1, 0x64, 0xaa, 0xf2, 0xee, 0x40, 0x7e, 0x05, 0xea,
	0x70, 0x8e, 0x60, 0x78, 0xe5, 0x36, 0x0e, 0xee, 0x66, 0x62, 0x27, 0xde, 0x04, 0xfb, 0xb6, 0xcb,
	0xb9, 0x54, 0x5d, 0xb2, 0x3f, 0xe9, 0x9b, 0x51, 0x3f, 0xe2, 0xcd, 0x3c, 0x84, 0xda, 0xe8, 0xdd,
	0x62, 0x1c, 0xcc, 0x23, 0x2c, 0x65, 0xa5, 0x28, 0x2e, 0x70, 0x27, 0x7c, 0x5a, 0x8b, 0x12, 0xb9,
	0xc2, 0x33, 0xab, 0xad, 0x3c, 0xb3, 0x47, 0xd0, 0x10, 0xb7, 0xae, 0x1e, 0x45, 0x8d, 0x37, 0x99,
	0x14, 0x79, 0x00, 0x37, 0x73, 0x97, 0x78, 0x59, 0x26, 0x23, 0xe9, 0xe6, 0x9b, 0x22, 0x19, 0x9b,
	0x7a, 0x95, 0x3b, 0x1a, 0xb5, 0x80, 0x83, 0xfd, 0x50, 0x1c, 0xaa, 0x3c, 0x0e, 0x0c, 0x0e, 0x0c,
	0x9d, 0x08, 0x07, 0xdb, 0xcc, 0x0d, 0xa3, 0x56, 0x83, 0xdf, 0xb9, 0x95, 0xdd, 0x91, 0x3c, 0x0a,
	0x4b, 0x29, 0x66, 0xfc, 0xb9, 0x02, 0x04, 0x73, 0xdd, 0x0f, 0xfc, 0x1e, 0xee, 0x0e, 0xe1, 0x87,
	0x72, 0xfe, 0x73, 0x68, 0xf6, 0x7b, 0x79, 0x67, 0xcb, 0x9c, 0xd5, 0xf4, 0xf3, 0x44, 0x4c, 0xdc,
	0x66, 0x41, 0x2a, 0xd7, 0xf8, 0x37, 0xfd, 0x55, 0x46, 0x9a, 0xb8, 0xca, 0x47, 0x24, 0xee, 0x04,
	0x74, 0xa9, 0xf8, 0x18, 0xd7, 0x15, 0x36, 0x13, 0x54, 0x1e, 0xee, 0x9d, 0xdc, 0x63, 0x28, 0xfa,
	0x20, 0xe4, 0xa8, 0xee, 0xaf, 0xdc, 0x24, 0x3d, 0xd0, 0x64, 0x30, 0x44, 0x21, 0xfc, 0xa6, 0xd0,
	0x03, 0x57, 0x34, 0x49, 0xcd, 0x43, 0x77, 0x8a, 0x2a, 0x42, 0xcf, 0xf1, 0xa9, 0x26, 0x63, 0x48,
	0xbe, 0x04, 0x4d, 0x82, 0xc3, 0x1a, 0xb9, 0xfe, 0xa5, 0x69, 0x12, 0xd1, 0xf6, 0x5f, 0x4a, 0x40,
	0xd6, 0xb5, 0xaf, 0x85, 0x5f, 0xb4, 0x98, 0xf2, 0x47, 0xb6, 0x18, 0x44, 0xc4, 0x3a, 0x93, 0x37,
	0xbe, 0x88, 0x5d, 0xd1, 0xd7, 0xae, 0x41, 0xe4, 0xa4, 0xe2, 0xc6, 0xbf, 0x4a, 0xb9, 0xe8, 0xac,
	0x01, 0xf9, 0x12, 0x9a, 0x92, 0xc9, 0x4c, 0x08, 0x48, 0xb7, 0x73, 0x65, 0x26, 0x1b, 0x23, 0x6d,
	0x2e, 0xf3, 0xa2, 0xf8, 0xfa, 0x2b, 0x6c, 0xb8, 0x88, 0xc7, 0xbf, 0xb9, 0x36, 0x75, 0x68, 0xe5,
	0x15, 0x9b, 0x89, 0x38, 0x37, 0x8f, 0x42, 0xef, 0x0d, 0xa6, 0x86, 0x55, 0x46, 0x9d, 0x56, 0xa7,
	0xfc, 0xf4, 0x09, 0xef, 0xdc, 0xf8, 0x4f, 0x09, 0x9a, 0xa8, 0xf4, 0x8a, 0x80, 0x7e, 0xc2, 0xa0,
	0xbd, 0x66, 0x14, 0x91, 0x03, 0x8c, 0x17, 0x33, 0xc4, 0xc3, 0x51, 0xb9, 0x22, 0x1c, 0xda, 0x32,
	0x15, 0x93, 0xa1, 0x50, 0xaf, 0x0c, 0x85, 0xf1, 0xdf, 0x32, 0xe8, 0xab, 0xfd, 0xf4, 0xb2, 0x35,
	0xe9, 0x30, 0x74, 0xfc, 0x29, 0x12, 0x93, 0x35, 0xa7, 0x36, 0x4e, 0x8e, 0x7c, 0x31, 0xbf, 0x18,
	0xa7, 0xcc, 0x64, 0xd9, 0x81, 0x48, 0x52, 0xd8, 0x66, 0xcc, 0xd5, 0x9e, 0xbb, 0x0e, 0xdb, 0xee,
	0x2a, 0x5c, 0xa0, 0xb1, 0xc8, 0x48, 0x2b, 0xbe, 0xab, 0x6b, 0xbe, 0xa7, 0x7b, 0x4f, 0x35, 0x19,
	0xdd, 0x7c, 0xef, 0xc1, 0xa5, 0x8b, 0x1b, 0x10, 0xed, 0x52, 0xe5, 0x68, 0xf8, 0x07, 0x84, 0xb0,
	0xcc, 0x1b, 0x25, 0xf6, 0xd1, 0x14, 0x09, 0xdb, 0x31, 0x24, 0x0e, 0xd1, 0x0c, 0x35, 0x89, 0x82,
	0xd5, 0x03, 0xb3, 0x81, 0x00, 0x21, 0x59, 0xd7, 0x62, 0x7e, 0x62, 0x76, 0xf8, 0x2d, 0xec, 0x74,
	0xdc, 0x0e, 0xbf, 0xc1, 0xa4, 0x2d, 0x5c, 0xa3, 0x9d, 0x69, 0x6b, 0x23, 0x91, 0xf6, 0xf8, 0xc9,
	0xf8, 0x6b, 0x19, 0x36, 0xf2, 0x5d, 0x93, 0x19, 0xe5, 0x3f, 0x6c, 0xf7, 0x6d, 0x2c, 0x56, 0x46,
	0x6d, 0x99, 0x12, 0xb2, 0x49, 0x55, 0xbe, 0x72, 0x52, 0x65, 0xd8, 0x94, 0x02, 0x36, 0xf4, 0x56,
	0xf6, 0xbf, 0x64, 0x9f, 0xac, 0xc7, 0x69, 0xdb, 0xbb, 0x2e, 0xa6, 0xf9, 0x5d, 0xbe, 0xfa, 0x11,
	0xbb, 0xfc, 0x13, 0xd8, 0x3a, 0x09, 0x26, 0xce, 0x7c, 0x18, 0x06, 0x6f, 0x3c, 0x54, 0xb0, 0xf6,
	0xe5, 0xb0, 0x35, 0xbf, 0x9c, 0x6d, 0x7c, 0x0d, 0xcd, 0xc2, 0xd4, 0xe3, 0x49, 0xe2, 0xbf, 0xe4,
	0x16, 0x55, 0x8f, 0xc4, 0x99, 0x17, 0x13, 0xff, 0x9d, 0xdb, 0xa4, 0x20, 0x92, 0x14, 0xb2, 0x9b,
	0xcd, 0xd6, 0xa4, 0xe3, 0xe8, 0x19, 0xea, 0x95, 0xa1, 0x6a, 0xbc, 0x80, 0xaa, 0xb0, 0xf8, 0xa9,
	0x1f, 0x2e, 0xd7, 0x7c, 0x72, 0x18, 0x13, 0x68, 0x8e, 0xb0, 0x95, 0xe2, 0xe3, 0xe5, 0x62, 0x33,
	0xf6, 0x3a, 0xcc, 0xe9, 0x14, 0xa7, 0x75, 0x24, 0x92, 0x5c, 0x73, 0x92, 0x23, 0x8e, 0xb4, 0x8a,
	0x9c, 0x64, 0x37, 0xf2, 0x68, 0x8f, 0x0e, 0xf9, 0xd4, 0x4e, 0xaa, 0x99, 0x55, 0xb8, 0x33, 0x4b,
	0x7c, 0x62, 0x15, 0x8e, 0xbf, 0x8d, 0xbf, 0xe1, 0xfe, 0x27, 0x02, 0x87, 0x23, 0x1e, 0xb7, 0x8a,
	0x7a, 0xfa, 0x85, 0x2d, 0x7c, 0xc8, 0x6d, 0xd4, 0xb9, 0xcf, 0x6f, 0x5a, 0x5f, 0xa4, 0x1f, 0xe2,
	0xd7, 0x7f, 0x7f, 0x61, 0x64, 0x6a, 0xe9, 0x4c, 0x49, 0xe2, 0x79, 0xbb, 0xd0, 0x25, 0x04, 0x8f,
	0xd6, 0xc4, 0xd6, 0x60, 0xfc, 0x1d, 0x7b, 0x5e, 0xd6, 0xf0, 0x7e, 0x38, 0x5c, 0x5f, 0xb0, 0xdd,
	0x37, 0x35, 0x23, 0xa0, 0x6d, 0x15, 0xa0, 0xe5, 0xa6, 0x24, 0x2c, 0xe5, 0xef, 0xdd, 0x7f, 0x2b,
	0xf2, 0xab, 0x1d, 0xdf, 0xae, 0x3e, 0x38, 0xfc, 0xea, 0xa5, 0x7d, 0x3e, 0xec, 0xbc, 0x3c, 0xed,
	0x3f, 0xeb, 0x0f, 0x9e, 0xf7, 0xf5, 0x1f, 0xe1, 0x07, 0xd8, 0x86, 0xa4, 0xb6, 0x4d, 0xaa, 0x97,
	0x0a, 0x72, 0x87, 0x56, 0xfb, 0xbc, 0x7d, 0xd2, 0xd1, 0xcb, 0xe4, 0x0e, 0x6c, 0x4a, 0xaa, 0x4d,
	0x05, 0x59, 0x21, 0x5b, 0x70, 0x4b, 0x92, 0x87, 0x9d, 0xa3, 0xce, 0x08, 0x79, 0x66, 0x5f, 0xaf,
	0x60, 0x0e, 0x9b, 0x92, 0xd1, 0x35, 0xdb, 0x1d, 0xfd, 0x7d, 0x1d, 0x9f, 0xff, 0x96, 0xa4, 0x9d,
	0x75, 0x9e, 0x5a, 0xa8, 0x02, 0xff, 0xb6, 0xed, 0x01, 0xd5, 0xdf, 0xeb, 0x05, 0xae, 0xb0, 0x9b,
	0x72, 0xbf, 0xd1, 0xc9, 0x8f, 0xa1, 0xb5, 0x66, 0x3f, 0x65, 0x7f, 0xab, 0x93, 0x9f, 0xc2, 0xf6,
	0x25, 0x38, 0x52, 0x81, 0xef, 0x74, 0x72, 0x0f, 0x6e, 0x17, 0xf0, 0x48, 0xc3, 0x2d, 0xac, 0xef,
	0x7b, 0x6b, 0xb0, 0xda, 0xa7, 0xf6, 0xe1, 0xc0, 0xa4, 0x47, 0xfa, 0xfb, 0x9d, 0x02, 0x3f, 0x05,
	0x26, 0xf9, 0xdf, 0xec, 0x14, 0x6c, 0x4b, 0x68, 0x52, 0xe0, 0xdb, 0x1d, 0xcc, 0xf0, 0xfd, 0xcb,
	0xc0, 0x49, 0x91, 0xef, 0x76, 0xc8, 0x67, 0x70, 0xb7, 0x08, 0x2f, 0x03, 0xf0, 0x60, 0xf7, 0x18,
	0x1a, 0xec, 0x03, 0xb8, 0xbb, 0x88, 0xc5, 0x30, 0x02, 0x91, 0xbf, 0x6e, 0xcf, 0xc6, 0x14, 0xd6,
	0xa1, 0xf2, 0xd5, 0x68, 0xd0, 0xc7, 0xd4, 0x6d, 0x40, 0x7d, 0x48, 0x07, 0xf6, 0xe0, 0xf0, 0xb4,
	0x8b, 0x29, 0xab, 0x81, 0xd2, 0x1e, 0x9d, 0x61, 0x92, 0xf0, 0xc7, 0xf0, 0xa8, 0xab, 0x57, 0x50,
	0x51, 0x0d, 0x57, 0x9a, 0xb4, 0x1a, 0x46, 0x9d, 0x17, 0xab, 0xd5, 0xb0, 0x89, 0x4f, 0x39, 0xa5,
	0xf6, 0x4c, 0xcc, 0x70, 0x89, 0xdc, 0x82, 0x9b, 0x92, 0xd4, 0xed, 0x70, 0x62, 0x79, 0xf7, 0x77,
	0xb0, 0x91, 0x7e, 0x20, 0x71, 0x6d, 0xf7, 0xe0, 0x4e, 0xdf, 0xb4, 0xad, 0x41, 0xdf, 0x3c, 0x59,
	0x55, 0x89, 0x85, 0x53, 0x64, 0x3d, 0x35, 0x19, 0xd4, 0x6d, 0xb8, 0x5b, 0x24, 0xf7, 0xac, 0xfe,
	0x80, 0x5a, 0xf6, 0x39, 0x6a, 0xff, 0x03, 0xf6, 0x8f, 0x99, 0x9b, 0xc2, 0x34, 0x8f, 0x3b, 0x97,
	0xc0, 0x94, 0xd4, 0x13, 0xfb, 0xe1, 0x63, 0xd4, 0x97, 0x27, 0x3d, 0x7c, 0xfc, 0x68, 0x1f, 0xfd,
	0xcf, 0x93, 0x1e, 0xed, 0x3f, 0xde, 0xc7, 0x48, 0xe4, 0x49, 0x8f, 0xf7, 0x4f, 0x87, 0x18, 0x13,
	0x0f, 0x81, 0x5c, 0xba, 0xc4, 0x32, 0xe4, 0xa6, 0x6d, 0x5b, 0xf6, 0xe9, 0x11, 0xa6, 0x6d, 0x30,
	0xb2, 0x6c, 0xeb, 0xac, 0x83, 0xc6, 0x09, 0xdc, 0x90, 0x64, 0x6a, 0x1d, 0x3f, 0xb5, 0x85, 0xf5,
	0x94, 0x76, 0xd2, 0xe9, 0xda, 0xc2, 0x7a, 0x4a, 0x3a, 0x34, 0xdb, 0xcf, 0x74, 0x65, 0x77, 0x1f,
	0xb7, 0x2c, 0xde, 0xe7, 0x88, 0x06, 0xea, 0x33, 0xb3, 0xfb, 0xcc, 0x44, 0x75, 0x2c, 0x67, 0x83,
	0x91, 0x7d, 0x4c, 0x3b, 0x23, 0x54, 0xd4, 0x04, 0xad, 0x6b, 0x9d, 0x74, 0xac, 0x1e, 0xc2, 0xd4,
	0xcb, 0xe3, 0x2a, 0xff, 0xef, 0xe2, 0xa3, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x01, 0x4e, 0x12,
	0x70, 0x6d, 0x14, 0x00, 0x00,
}
