// Code generated by protoc-gen-go.
// source: witness.proto
// DO NOT EDIT!

package dg_model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type IndexType int32

const (
	IndexType_INDEX_DEFAULT                   IndexType = 0
	IndexType_INDEX_CAR_BRAND                 IndexType = 1
	IndexType_INDEX_CAR_TYPE                  IndexType = 2
	IndexType_INDEX_CAR_COLOR                 IndexType = 3
	IndexType_INDEX_CAR_MARKER                IndexType = 4
	IndexType_INDEX_CAR_PLATE_TYPE            IndexType = 5
	IndexType_INDEX_CAR_PLATE_COLOR           IndexType = 6
	IndexType_INDEX_CAR_PEDESTRIAN_ATTR_TYPE  IndexType = 7
	IndexType_INDEX_NONMOTORVEHICLE_ATTR_TYPE IndexType = 8
)

var IndexType_name = map[int32]string{
	0: "INDEX_DEFAULT",
	1: "INDEX_CAR_BRAND",
	2: "INDEX_CAR_TYPE",
	3: "INDEX_CAR_COLOR",
	4: "INDEX_CAR_MARKER",
	5: "INDEX_CAR_PLATE_TYPE",
	6: "INDEX_CAR_PLATE_COLOR",
	7: "INDEX_CAR_PEDESTRIAN_ATTR_TYPE",
	8: "INDEX_NONMOTORVEHICLE_ATTR_TYPE",
}
var IndexType_value = map[string]int32{
	"INDEX_DEFAULT":                   0,
	"INDEX_CAR_BRAND":                 1,
	"INDEX_CAR_TYPE":                  2,
	"INDEX_CAR_COLOR":                 3,
	"INDEX_CAR_MARKER":                4,
	"INDEX_CAR_PLATE_TYPE":            5,
	"INDEX_CAR_PLATE_COLOR":           6,
	"INDEX_CAR_PEDESTRIAN_ATTR_TYPE":  7,
	"INDEX_NONMOTORVEHICLE_ATTR_TYPE": 8,
}

func (x IndexType) String() string {
	return proto.EnumName(IndexType_name, int32(x))
}
func (IndexType) EnumDescriptor() ([]byte, []int) { return fileDescriptor20, []int{0} }

type IndexRequest struct {
	IndexType IndexType `protobuf:"varint,1,opt,name=IndexType,json=indexType,enum=dg.model.IndexType" json:"IndexType"`
}

func (m *IndexRequest) Reset()                    { *m = IndexRequest{} }
func (m *IndexRequest) String() string            { return proto.CompactTextString(m) }
func (*IndexRequest) ProtoMessage()               {}
func (*IndexRequest) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{0} }

type IndexTxtRequest struct {
	IndexType IndexType `protobuf:"varint,1,opt,name=IndexType,json=indexType,enum=dg.model.IndexType" json:"IndexType"`
}

func (m *IndexTxtRequest) Reset()                    { *m = IndexTxtRequest{} }
func (m *IndexTxtRequest) String() string            { return proto.CompactTextString(m) }
func (*IndexTxtRequest) ProtoMessage()               {}
func (*IndexTxtRequest) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{1} }

type IndexTxtResponse struct {
	Context string `protobuf:"bytes,1,opt,name=Context,json=context" json:"Context"`
}

func (m *IndexTxtResponse) Reset()                    { *m = IndexTxtResponse{} }
func (m *IndexTxtResponse) String() string            { return proto.CompactTextString(m) }
func (*IndexTxtResponse) ProtoMessage()               {}
func (*IndexTxtResponse) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{2} }

type CommonIndex struct {
	Items []*CommonIndex_Item `protobuf:"bytes,1,rep,name=Items,json=items" json:"Items"`
}

func (m *CommonIndex) Reset()                    { *m = CommonIndex{} }
func (m *CommonIndex) String() string            { return proto.CompactTextString(m) }
func (*CommonIndex) ProtoMessage()               {}
func (*CommonIndex) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{3} }

func (m *CommonIndex) GetItems() []*CommonIndex_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type CommonIndex_Item struct {
	Id   int32  `protobuf:"varint,1,opt,name=Id,json=id" json:"Id"`
	Name string `protobuf:"bytes,2,opt,name=Name,json=name" json:"Name"`
}

func (m *CommonIndex_Item) Reset()                    { *m = CommonIndex_Item{} }
func (m *CommonIndex_Item) String() string            { return proto.CompactTextString(m) }
func (*CommonIndex_Item) ProtoMessage()               {}
func (*CommonIndex_Item) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{3, 0} }

type BrandIndex struct {
	Items []*BrandIndex_Item `protobuf:"bytes,1,rep,name=Items,json=items" json:"Items"`
}

func (m *BrandIndex) Reset()                    { *m = BrandIndex{} }
func (m *BrandIndex) String() string            { return proto.CompactTextString(m) }
func (*BrandIndex) ProtoMessage()               {}
func (*BrandIndex) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{4} }

func (m *BrandIndex) GetItems() []*BrandIndex_Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type BrandIndex_Item struct {
	MainBrandId   int32  `protobuf:"varint,2,opt,name=MainBrandId,json=mainBrandId" json:"MainBrandId"`
	SubBrandId    int32  `protobuf:"varint,3,opt,name=SubBrandId,json=subBrandId" json:"SubBrandId"`
	YearModelId   int32  `protobuf:"varint,4,opt,name=YearModelId,json=yearModelId" json:"YearModelId"`
	MainBrandName string `protobuf:"bytes,5,opt,name=MainBrandName,json=mainBrandName" json:"MainBrandName"`
	SubBrandName  string `protobuf:"bytes,6,opt,name=SubBrandName,json=subBrandName" json:"SubBrandName"`
	YearModelName string `protobuf:"bytes,7,opt,name=YearModelName,json=yearModelName" json:"YearModelName"`
}

func (m *BrandIndex_Item) Reset()                    { *m = BrandIndex_Item{} }
func (m *BrandIndex_Item) String() string            { return proto.CompactTextString(m) }
func (*BrandIndex_Item) ProtoMessage()               {}
func (*BrandIndex_Item) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{4, 0} }

type IndexResponse struct {
	// Types that are valid to be assigned to IndexContent:
	//	*IndexResponse_Index
	//	*IndexResponse_BrandIndex
	IndexContent isIndexResponse_IndexContent `protobuf_oneof:"index_content"`
}

func (m *IndexResponse) Reset()                    { *m = IndexResponse{} }
func (m *IndexResponse) String() string            { return proto.CompactTextString(m) }
func (*IndexResponse) ProtoMessage()               {}
func (*IndexResponse) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{5} }

type isIndexResponse_IndexContent interface {
	isIndexResponse_IndexContent()
}

type IndexResponse_Index struct {
	Index *CommonIndex `protobuf:"bytes,1,opt,name=Index,json=index,oneof"`
}
type IndexResponse_BrandIndex struct {
	BrandIndex *BrandIndex `protobuf:"bytes,2,opt,name=BrandIndex,json=brandIndex,oneof"`
}

func (*IndexResponse_Index) isIndexResponse_IndexContent()      {}
func (*IndexResponse_BrandIndex) isIndexResponse_IndexContent() {}

func (m *IndexResponse) GetIndexContent() isIndexResponse_IndexContent {
	if m != nil {
		return m.IndexContent
	}
	return nil
}

func (m *IndexResponse) GetIndex() *CommonIndex {
	if x, ok := m.GetIndexContent().(*IndexResponse_Index); ok {
		return x.Index
	}
	return nil
}

func (m *IndexResponse) GetBrandIndex() *BrandIndex {
	if x, ok := m.GetIndexContent().(*IndexResponse_BrandIndex); ok {
		return x.BrandIndex
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*IndexResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _IndexResponse_OneofMarshaler, _IndexResponse_OneofUnmarshaler, _IndexResponse_OneofSizer, []interface{}{
		(*IndexResponse_Index)(nil),
		(*IndexResponse_BrandIndex)(nil),
	}
}

func _IndexResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*IndexResponse)
	// index_content
	switch x := m.IndexContent.(type) {
	case *IndexResponse_Index:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Index); err != nil {
			return err
		}
	case *IndexResponse_BrandIndex:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BrandIndex); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("IndexResponse.IndexContent has unexpected type %T", x)
	}
	return nil
}

func _IndexResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*IndexResponse)
	switch tag {
	case 1: // index_content.Index
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CommonIndex)
		err := b.DecodeMessage(msg)
		m.IndexContent = &IndexResponse_Index{msg}
		return true, err
	case 2: // index_content.BrandIndex
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BrandIndex)
		err := b.DecodeMessage(msg)
		m.IndexContent = &IndexResponse_BrandIndex{msg}
		return true, err
	default:
		return false, nil
	}
}

func _IndexResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*IndexResponse)
	// index_content
	switch x := m.IndexContent.(type) {
	case *IndexResponse_Index:
		s := proto.Size(x.Index)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *IndexResponse_BrandIndex:
		s := proto.Size(x.BrandIndex)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type WitnessRequest struct {
	Context *WitnessRequestContext `protobuf:"bytes,1,opt,name=Context,json=context" json:"Context"`
	Image   *WitnessImage          `protobuf:"bytes,2,opt,name=Image,json=image" json:"Image"`
}

func (m *WitnessRequest) Reset()                    { *m = WitnessRequest{} }
func (m *WitnessRequest) String() string            { return proto.CompactTextString(m) }
func (*WitnessRequest) ProtoMessage()               {}
func (*WitnessRequest) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{6} }

func (m *WitnessRequest) GetContext() *WitnessRequestContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *WitnessRequest) GetImage() *WitnessImage {
	if m != nil {
		return m.Image
	}
	return nil
}

type WitnessBatchRequest struct {
	Context *WitnessRequestContext `protobuf:"bytes,1,opt,name=Context,json=context" json:"Context"`
	Images  []*WitnessImage        `protobuf:"bytes,2,rep,name=Images,json=images" json:"Images"`
}

func (m *WitnessBatchRequest) Reset()                    { *m = WitnessBatchRequest{} }
func (m *WitnessBatchRequest) String() string            { return proto.CompactTextString(m) }
func (*WitnessBatchRequest) ProtoMessage()               {}
func (*WitnessBatchRequest) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{7} }

func (m *WitnessBatchRequest) GetContext() *WitnessRequestContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *WitnessBatchRequest) GetImages() []*WitnessImage {
	if m != nil {
		return m.Images
	}
	return nil
}

type WitnessResponse struct {
	Context *WitnessResponseContext `protobuf:"bytes,1,opt,name=Context,json=context" json:"Context"`
	Result  *WitnessResult          `protobuf:"bytes,2,opt,name=Result,json=result" json:"Result"`
}

func (m *WitnessResponse) Reset()                    { *m = WitnessResponse{} }
func (m *WitnessResponse) String() string            { return proto.CompactTextString(m) }
func (*WitnessResponse) ProtoMessage()               {}
func (*WitnessResponse) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{8} }

func (m *WitnessResponse) GetContext() *WitnessResponseContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *WitnessResponse) GetResult() *WitnessResult {
	if m != nil {
		return m.Result
	}
	return nil
}

type WitnessBatchResponse struct {
	Context *WitnessResponseContext `protobuf:"bytes,1,opt,name=Context,json=context" json:"Context"`
	Results []*WitnessResult        `protobuf:"bytes,2,rep,name=Results,json=results" json:"Results"`
}

func (m *WitnessBatchResponse) Reset()                    { *m = WitnessBatchResponse{} }
func (m *WitnessBatchResponse) String() string            { return proto.CompactTextString(m) }
func (*WitnessBatchResponse) ProtoMessage()               {}
func (*WitnessBatchResponse) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{9} }

func (m *WitnessBatchResponse) GetContext() *WitnessResponseContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *WitnessBatchResponse) GetResults() []*WitnessResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type WitnessRelativeROI struct {
	PosX   int32 `protobuf:"varint,1,opt,name=PosX,json=posX" json:"PosX"`
	PosY   int32 `protobuf:"varint,2,opt,name=PosY,json=posY" json:"PosY"`
	Width  int32 `protobuf:"varint,3,opt,name=Width,json=width" json:"Width"`
	Height int32 `protobuf:"varint,4,opt,name=Height,json=height" json:"Height"`
}

func (m *WitnessRelativeROI) Reset()                    { *m = WitnessRelativeROI{} }
func (m *WitnessRelativeROI) String() string            { return proto.CompactTextString(m) }
func (*WitnessRelativeROI) ProtoMessage()               {}
func (*WitnessRelativeROI) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{10} }

type WitnessMarginROI struct {
	Left   int32 `protobuf:"varint,1,opt,name=Left,json=left" json:"Left"`
	Top    int32 `protobuf:"varint,2,opt,name=Top,json=top" json:"Top"`
	Right  int32 `protobuf:"varint,3,opt,name=Right,json=right" json:"Right"`
	Bottom int32 `protobuf:"varint,4,opt,name=Bottom,json=bottom" json:"Bottom"`
}

func (m *WitnessMarginROI) Reset()                    { *m = WitnessMarginROI{} }
func (m *WitnessMarginROI) String() string            { return proto.CompactTextString(m) }
func (*WitnessMarginROI) ProtoMessage()               {}
func (*WitnessMarginROI) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{11} }

type WitnessRequestContext struct {
	SessionId string               `protobuf:"bytes,1,opt,name=SessionId,json=sessionId" json:"SessionId"`
	UserName  string               `protobuf:"bytes,2,opt,name=UserName,json=userName" json:"UserName"`
	Token     string               `protobuf:"bytes,3,opt,name=Token,json=token" json:"Token"`
	Functions []RecognizeFunctions `protobuf:"varint,4,rep,packed,name=Functions,json=functions,enum=dg.model.RecognizeFunctions" json:"Functions"`
	Type      RecognizeType        `protobuf:"varint,5,opt,name=Type,json=type,enum=dg.model.RecognizeType" json:"Type"`
	Storages  []*StorageConfig     `protobuf:"bytes,6,rep,name=Storages,json=storages" json:"Storages"`
	Params    map[string]string    `protobuf:"bytes,7,rep,name=Params,json=params" json:"Params" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *WitnessRequestContext) Reset()                    { *m = WitnessRequestContext{} }
func (m *WitnessRequestContext) String() string            { return proto.CompactTextString(m) }
func (*WitnessRequestContext) ProtoMessage()               {}
func (*WitnessRequestContext) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{12} }

func (m *WitnessRequestContext) GetStorages() []*StorageConfig {
	if m != nil {
		return m.Storages
	}
	return nil
}

func (m *WitnessRequestContext) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type WitnessImage struct {
	Data            *Image                `protobuf:"bytes,1,opt,name=Data,json=data" json:"Data"`
	WitnessMetaData *SrcMetadata          `protobuf:"bytes,2,opt,name=WitnessMetaData,json=witnessMetaData" json:"WitnessMetaData"`
	RelativeRoi     []*WitnessRelativeROI `protobuf:"bytes,3,rep,name=RelativeRoi,json=relativeRoi" json:"RelativeRoi"`
	MarginRoi       []*WitnessMarginROI   `protobuf:"bytes,4,rep,name=MarginRoi,json=marginRoi" json:"MarginRoi"`
}

func (m *WitnessImage) Reset()                    { *m = WitnessImage{} }
func (m *WitnessImage) String() string            { return proto.CompactTextString(m) }
func (*WitnessImage) ProtoMessage()               {}
func (*WitnessImage) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{13} }

func (m *WitnessImage) GetData() *Image {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *WitnessImage) GetWitnessMetaData() *SrcMetadata {
	if m != nil {
		return m.WitnessMetaData
	}
	return nil
}

func (m *WitnessImage) GetRelativeRoi() []*WitnessRelativeROI {
	if m != nil {
		return m.RelativeRoi
	}
	return nil
}

func (m *WitnessImage) GetMarginRoi() []*WitnessMarginROI {
	if m != nil {
		return m.MarginRoi
	}
	return nil
}

type WitnessResponseContext struct {
	SessionId  string           `protobuf:"bytes,1,opt,name=SessionId,json=sessionId" json:"SessionId"`
	Status     string           `protobuf:"bytes,2,opt,name=Status,json=status" json:"Status"`
	Message    string           `protobuf:"bytes,3,opt,name=Message,json=message" json:"Message"`
	RequestTs  *Time            `protobuf:"bytes,4,opt,name=RequestTs,json=requestTs" json:"RequestTs"`
	ResponseTs *Time            `protobuf:"bytes,5,opt,name=ResponseTs,json=responseTs" json:"ResponseTs"`
	DebugTs    map[string]*Time `protobuf:"bytes,6,rep,name=DebugTs,json=debugTs" json:"DebugTs" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *WitnessResponseContext) Reset()                    { *m = WitnessResponseContext{} }
func (m *WitnessResponseContext) String() string            { return proto.CompactTextString(m) }
func (*WitnessResponseContext) ProtoMessage()               {}
func (*WitnessResponseContext) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{14} }

func (m *WitnessResponseContext) GetRequestTs() *Time {
	if m != nil {
		return m.RequestTs
	}
	return nil
}

func (m *WitnessResponseContext) GetResponseTs() *Time {
	if m != nil {
		return m.ResponseTs
	}
	return nil
}

func (m *WitnessResponseContext) GetDebugTs() map[string]*Time {
	if m != nil {
		return m.DebugTs
	}
	return nil
}

type WitnessResult struct {
	InnerStatus      string                `protobuf:"bytes,1,opt,name=InnerStatus,json=innerStatus" json:"InnerStatus"`
	InnerMessage     string                `protobuf:"bytes,2,opt,name=InnerMessage,json=innerMessage" json:"InnerMessage"`
	Image            *WitnessImage         `protobuf:"bytes,3,opt,name=Image,json=image" json:"Image"`
	Vehicles         []*RecVehicle         `protobuf:"bytes,4,rep,name=Vehicles,json=vehicles" json:"Vehicles"`
	Pedestrian       []*RecPedestrian      `protobuf:"bytes,5,rep,name=Pedestrian,json=pedestrian" json:"Pedestrian"`
	NonMotorVehicles []*RecNonMotorVehicle `protobuf:"bytes,6,rep,name=NonMotorVehicles,json=nonMotorVehicles" json:"NonMotorVehicles"`
}

func (m *WitnessResult) Reset()                    { *m = WitnessResult{} }
func (m *WitnessResult) String() string            { return proto.CompactTextString(m) }
func (*WitnessResult) ProtoMessage()               {}
func (*WitnessResult) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{15} }

func (m *WitnessResult) GetImage() *WitnessImage {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *WitnessResult) GetVehicles() []*RecVehicle {
	if m != nil {
		return m.Vehicles
	}
	return nil
}

func (m *WitnessResult) GetPedestrian() []*RecPedestrian {
	if m != nil {
		return m.Pedestrian
	}
	return nil
}

func (m *WitnessResult) GetNonMotorVehicles() []*RecNonMotorVehicle {
	if m != nil {
		return m.NonMotorVehicles
	}
	return nil
}

func init() {
	proto.RegisterType((*IndexRequest)(nil), "dg.model.IndexRequest")
	proto.RegisterType((*IndexTxtRequest)(nil), "dg.model.IndexTxtRequest")
	proto.RegisterType((*IndexTxtResponse)(nil), "dg.model.IndexTxtResponse")
	proto.RegisterType((*CommonIndex)(nil), "dg.model.CommonIndex")
	proto.RegisterType((*CommonIndex_Item)(nil), "dg.model.CommonIndex.Item")
	proto.RegisterType((*BrandIndex)(nil), "dg.model.BrandIndex")
	proto.RegisterType((*BrandIndex_Item)(nil), "dg.model.BrandIndex.Item")
	proto.RegisterType((*IndexResponse)(nil), "dg.model.IndexResponse")
	proto.RegisterType((*WitnessRequest)(nil), "dg.model.WitnessRequest")
	proto.RegisterType((*WitnessBatchRequest)(nil), "dg.model.WitnessBatchRequest")
	proto.RegisterType((*WitnessResponse)(nil), "dg.model.WitnessResponse")
	proto.RegisterType((*WitnessBatchResponse)(nil), "dg.model.WitnessBatchResponse")
	proto.RegisterType((*WitnessRelativeROI)(nil), "dg.model.WitnessRelativeROI")
	proto.RegisterType((*WitnessMarginROI)(nil), "dg.model.WitnessMarginROI")
	proto.RegisterType((*WitnessRequestContext)(nil), "dg.model.WitnessRequestContext")
	proto.RegisterType((*WitnessImage)(nil), "dg.model.WitnessImage")
	proto.RegisterType((*WitnessResponseContext)(nil), "dg.model.WitnessResponseContext")
	proto.RegisterType((*WitnessResult)(nil), "dg.model.WitnessResult")
	proto.RegisterEnum("dg.model.IndexType", IndexType_name, IndexType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for WitnessService service

type WitnessServiceClient interface {
	Recognize(ctx context.Context, in *WitnessRequest, opts ...grpc.CallOption) (*WitnessResponse, error)
	BatchRecognize(ctx context.Context, in *WitnessBatchRequest, opts ...grpc.CallOption) (*WitnessBatchResponse, error)
	GetIndex(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error)
	GetIndexTxt(ctx context.Context, in *IndexTxtRequest, opts ...grpc.CallOption) (*IndexTxtResponse, error)
}

type witnessServiceClient struct {
	cc *grpc.ClientConn
}

func NewWitnessServiceClient(cc *grpc.ClientConn) WitnessServiceClient {
	return &witnessServiceClient{cc}
}

func (c *witnessServiceClient) Recognize(ctx context.Context, in *WitnessRequest, opts ...grpc.CallOption) (*WitnessResponse, error) {
	out := new(WitnessResponse)
	err := grpc.Invoke(ctx, "/dg.model.WitnessService/Recognize", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *witnessServiceClient) BatchRecognize(ctx context.Context, in *WitnessBatchRequest, opts ...grpc.CallOption) (*WitnessBatchResponse, error) {
	out := new(WitnessBatchResponse)
	err := grpc.Invoke(ctx, "/dg.model.WitnessService/BatchRecognize", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *witnessServiceClient) GetIndex(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error) {
	out := new(IndexResponse)
	err := grpc.Invoke(ctx, "/dg.model.WitnessService/GetIndex", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *witnessServiceClient) GetIndexTxt(ctx context.Context, in *IndexTxtRequest, opts ...grpc.CallOption) (*IndexTxtResponse, error) {
	out := new(IndexTxtResponse)
	err := grpc.Invoke(ctx, "/dg.model.WitnessService/GetIndexTxt", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WitnessService service

type WitnessServiceServer interface {
	Recognize(context.Context, *WitnessRequest) (*WitnessResponse, error)
	BatchRecognize(context.Context, *WitnessBatchRequest) (*WitnessBatchResponse, error)
	GetIndex(context.Context, *IndexRequest) (*IndexResponse, error)
	GetIndexTxt(context.Context, *IndexTxtRequest) (*IndexTxtResponse, error)
}

func RegisterWitnessServiceServer(s *grpc.Server, srv WitnessServiceServer) {
	s.RegisterService(&_WitnessService_serviceDesc, srv)
}

func _WitnessService_Recognize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WitnessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WitnessServiceServer).Recognize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dg.model.WitnessService/Recognize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WitnessServiceServer).Recognize(ctx, req.(*WitnessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WitnessService_BatchRecognize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WitnessBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WitnessServiceServer).BatchRecognize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dg.model.WitnessService/BatchRecognize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WitnessServiceServer).BatchRecognize(ctx, req.(*WitnessBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WitnessService_GetIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WitnessServiceServer).GetIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dg.model.WitnessService/GetIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WitnessServiceServer).GetIndex(ctx, req.(*IndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WitnessService_GetIndexTxt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexTxtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WitnessServiceServer).GetIndexTxt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dg.model.WitnessService/GetIndexTxt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WitnessServiceServer).GetIndexTxt(ctx, req.(*IndexTxtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WitnessService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dg.model.WitnessService",
	HandlerType: (*WitnessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recognize",
			Handler:    _WitnessService_Recognize_Handler,
		},
		{
			MethodName: "BatchRecognize",
			Handler:    _WitnessService_BatchRecognize_Handler,
		},
		{
			MethodName: "GetIndex",
			Handler:    _WitnessService_GetIndex_Handler,
		},
		{
			MethodName: "GetIndexTxt",
			Handler:    _WitnessService_GetIndexTxt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor20,
}

func init() { proto.RegisterFile("witness.proto", fileDescriptor20) }

var fileDescriptor20 = []byte{
	// 1325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x57, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x8e, 0x4e, 0x94, 0x34, 0x94, 0x6d, 0xfd, 0x1b, 0xc7, 0xb1, 0x85, 0xfc, 0x49, 0xc0, 0xe6,
	0x22, 0xc8, 0x41, 0x69, 0x14, 0xa0, 0x4d, 0x02, 0xb4, 0x85, 0x6c, 0x29, 0xb1, 0x5a, 0x4b, 0x76,
	0x57, 0xcc, 0xc1, 0x57, 0x06, 0x2d, 0xae, 0x65, 0x36, 0x26, 0xa9, 0x92, 0x2b, 0xc7, 0xea, 0x45,
	0xd1, 0x9b, 0xa0, 0xef, 0xd0, 0x87, 0xe8, 0x75, 0x9f, 0xa5, 0x7d, 0x87, 0xa2, 0x8f, 0xd0, 0x3d,
	0xf1, 0x20, 0x5a, 0xae, 0x0b, 0x34, 0x37, 0xd2, 0xce, 0xcc, 0x37, 0x87, 0x9d, 0x9d, 0x99, 0x5d,
	0xc2, 0xd2, 0x7b, 0x87, 0x7a, 0x24, 0x0c, 0x9b, 0x93, 0xc0, 0xa7, 0x3e, 0xaa, 0xd8, 0xe3, 0xa6,
	0xeb, 0xdb, 0xe4, 0xa4, 0x51, 0x1b, 0xf9, 0xae, 0xeb, 0x7b, 0x92, 0xdf, 0xa8, 0xb9, 0x16, 0x0d,
	0x9c, 0x33, 0x49, 0x19, 0x6d, 0xa8, 0xf5, 0x3c, 0x9b, 0x9c, 0x61, 0xf2, 0xfd, 0x94, 0x84, 0x14,
	0x3d, 0x86, 0xaa, 0xa0, 0xcd, 0xd9, 0x84, 0xac, 0xe7, 0x6e, 0xe7, 0xee, 0x2e, 0xb7, 0xae, 0x36,
	0x23, 0x4b, 0xcd, 0x58, 0x84, 0xab, 0x4e, 0xb4, 0x34, 0x3a, 0xb0, 0x22, 0xf9, 0x67, 0xf4, 0x3f,
	0x58, 0x79, 0x00, 0xf5, 0xc4, 0x4a, 0x38, 0xf1, 0xbd, 0x90, 0xa0, 0x75, 0x28, 0x6f, 0xf9, 0x1e,
	0x25, 0x67, 0x54, 0x18, 0xa9, 0xe2, 0xf2, 0x48, 0x92, 0xc6, 0x3b, 0xd0, 0xb7, 0xc4, 0xa6, 0x84,
	0x0e, 0xfa, 0x14, 0x4a, 0x3d, 0x4a, 0xdc, 0x90, 0xc1, 0x0a, 0x77, 0xf5, 0x56, 0x23, 0xf1, 0x95,
	0x42, 0x35, 0x39, 0x04, 0x97, 0x1c, 0x0e, 0x6c, 0xdc, 0x83, 0x22, 0x27, 0xd1, 0x32, 0xe4, 0x7b,
	0xb6, 0xb0, 0x5e, 0xc2, 0x79, 0xc7, 0x46, 0x08, 0x8a, 0x03, 0xcb, 0x25, 0xeb, 0x79, 0xe1, 0xaf,
	0xe8, 0xb1, 0xb5, 0xf1, 0x4b, 0x1e, 0x60, 0x33, 0xb0, 0x3c, 0x5b, 0x3a, 0x7b, 0x34, 0xef, 0x6c,
	0x23, 0x71, 0x96, 0x80, 0xe6, 0x7c, 0xfd, 0x9e, 0x53, 0xce, 0x6e, 0x83, 0xde, 0xb7, 0x1c, 0x4f,
	0xc2, 0x6c, 0xe1, 0xa3, 0x84, 0x75, 0x37, 0x61, 0xa1, 0x9b, 0x00, 0xc3, 0xe9, 0x61, 0x04, 0x28,
	0x08, 0x00, 0x84, 0x31, 0x87, 0x5b, 0xd8, 0x27, 0x56, 0xd0, 0xe7, 0xee, 0x18, 0xa0, 0x28, 0x2d,
	0xcc, 0x12, 0x16, 0xba, 0x03, 0x4b, 0xb1, 0x0f, 0xb1, 0x93, 0x92, 0xd8, 0xc9, 0x92, 0x9b, 0x66,
	0x22, 0x03, 0x6a, 0x91, 0x1f, 0x01, 0xd2, 0x04, 0xa8, 0x16, 0xa6, 0x78, 0xdc, 0x52, 0xec, 0x4b,
	0x80, 0xca, 0xd2, 0xd2, 0x2c, 0xcd, 0x34, 0x7e, 0xce, 0xc1, 0x92, 0xaa, 0x20, 0x75, 0x6a, 0x0f,
	0x59, 0x7e, 0x38, 0x43, 0x64, 0x55, 0x6f, 0x5d, 0x5b, 0x78, 0x18, 0xdb, 0x57, 0x58, 0x76, 0x44,
	0x3a, 0x3f, 0x4b, 0x27, 0x57, 0xe4, 0x44, 0x6f, 0xad, 0x2e, 0xca, 0x29, 0x53, 0x81, 0xc3, 0x98,
	0xda, 0x5c, 0x81, 0x25, 0x61, 0xe0, 0x40, 0xd4, 0x84, 0x47, 0x8d, 0x19, 0x2c, 0xbf, 0x91, 0x1d,
	0x10, 0x95, 0xe1, 0xb3, 0xf9, 0xfa, 0xd1, 0x5b, 0xb7, 0x12, 0xbb, 0xf3, 0x50, 0x05, 0x8b, 0x0b,
	0x0c, 0x3d, 0x60, 0x9b, 0x70, 0xad, 0x31, 0x51, 0x01, 0xad, 0x9d, 0x53, 0x14, 0x52, 0xb6, 0x07,
	0xfe, 0x67, 0xfc, 0x94, 0x83, 0xab, 0x8a, 0xbf, 0x69, 0xd1, 0xd1, 0xf1, 0x47, 0x08, 0xa0, 0x09,
	0x9a, 0x70, 0x11, 0xb2, 0x08, 0x0a, 0xff, 0x10, 0x81, 0x26, 0x22, 0x08, 0x8d, 0x1f, 0x61, 0x25,
	0xb6, 0xa8, 0x0e, 0xe2, 0x79, 0xd6, 0xfb, 0xed, 0x05, 0xde, 0x25, 0xf6, 0x9c, 0xfb, 0x47, 0xa0,
	0x31, 0xd9, 0xf4, 0x84, 0xaa, 0x04, 0x5c, 0x5f, 0xa4, 0xca, 0xc4, 0x58, 0x0b, 0xc4, 0xbf, 0xf1,
	0x21, 0x07, 0xab, 0xf3, 0x29, 0xf8, 0x08, 0x51, 0x3c, 0x86, 0xb2, 0x74, 0x13, 0x65, 0xe1, 0xc2,
	0x30, 0xca, 0x32, 0x8c, 0xd0, 0xf8, 0x0e, 0x50, 0x2c, 0x39, 0xb1, 0xa8, 0x73, 0x4a, 0xf0, 0x6e,
	0x8f, 0xb7, 0xf5, 0x9e, 0x1f, 0xbe, 0x55, 0x8d, 0x5e, 0x9c, 0xb0, 0xb5, 0xe2, 0xed, 0xab, 0x36,
	0xe4, 0xbc, 0x7d, 0xb4, 0x0a, 0xa5, 0x37, 0x8e, 0x4d, 0x8f, 0x55, 0xeb, 0x95, 0xde, 0x73, 0x02,
	0xad, 0x81, 0xb6, 0x4d, 0x9c, 0xf1, 0x31, 0x55, 0x0d, 0xa7, 0x1d, 0x0b, 0xca, 0x38, 0x82, 0xba,
	0xf2, 0xd5, 0xb7, 0x82, 0xb1, 0xe3, 0x29, 0x4f, 0x3b, 0xe4, 0x88, 0x46, 0x9e, 0x4e, 0xd8, 0x1a,
	0xd5, 0xa1, 0x60, 0xfa, 0x13, 0xe5, 0xa8, 0x40, 0xfd, 0x09, 0xf7, 0x83, 0x85, 0x41, 0xe5, 0x27,
	0xe0, 0x04, 0xf7, 0xb3, 0xe9, 0x53, 0xea, 0xbb, 0x91, 0x9f, 0x43, 0x41, 0x19, 0x1f, 0x0a, 0x70,
	0x6d, 0x61, 0xb9, 0xa0, 0x1b, 0x50, 0x1d, 0x32, 0xae, 0xc3, 0xba, 0xca, 0x56, 0x33, 0xb2, 0x1a,
	0x46, 0x0c, 0xd4, 0x80, 0xca, 0xab, 0x90, 0x04, 0xa9, 0x81, 0x56, 0x99, 0x2a, 0x9a, 0x47, 0x60,
	0xfa, 0xef, 0x88, 0x27, 0x22, 0xa8, 0xe2, 0x12, 0xe5, 0x04, 0x3b, 0xac, 0xea, 0x8b, 0xa9, 0x37,
	0xa2, 0x4c, 0x3f, 0x64, 0x41, 0x14, 0xd8, 0xe0, 0xbe, 0x91, 0xa4, 0x1c, 0x93, 0x91, 0x3f, 0xf6,
	0x9c, 0x1f, 0x48, 0x8c, 0xc1, 0xd5, 0xa3, 0x68, 0x89, 0xee, 0x43, 0x51, 0xcc, 0xfb, 0x92, 0x98,
	0xf7, 0xd7, 0x17, 0xa8, 0x89, 0x99, 0x5f, 0xa4, 0xec, 0x17, 0x3d, 0x81, 0xca, 0x90, 0xfa, 0x81,
	0x28, 0x70, 0x2d, 0x7b, 0xb4, 0x4a, 0xc2, 0x36, 0x79, 0xe4, 0x8c, 0x71, 0x25, 0x54, 0x40, 0xb4,
	0x05, 0xda, 0x9e, 0x15, 0x58, 0x6c, 0xf4, 0x96, 0x85, 0xca, 0xfd, 0x4b, 0xba, 0xa9, 0x29, 0xd1,
	0x5d, 0x8f, 0x06, 0x33, 0xac, 0x4d, 0x04, 0xd1, 0x78, 0x06, 0x7a, 0x8a, 0xcd, 0xcf, 0xe6, 0x1d,
	0x99, 0xa9, 0xdc, 0xf1, 0x25, 0xcf, 0xcc, 0xa9, 0x75, 0x32, 0x8d, 0x52, 0x26, 0x89, 0xe7, 0xf9,
	0xa7, 0x39, 0xe3, 0xcf, 0x1c, 0xd4, 0xd2, 0xcd, 0x87, 0x3e, 0x81, 0x62, 0xc7, 0xa2, 0x96, 0x2a,
	0xec, 0x95, 0xd4, 0x15, 0x27, 0x7a, 0xb3, 0x68, 0x33, 0x21, 0xfa, 0x2a, 0xee, 0xcc, 0x3e, 0xa1,
	0x96, 0xc0, 0xe7, 0xb3, 0x93, 0x71, 0x18, 0x8c, 0xb8, 0x90, 0xe3, 0xf1, 0xca, 0xfb, 0x79, 0x34,
	0xfa, 0x12, 0xf4, 0xb8, 0x96, 0x7d, 0x87, 0x1d, 0x18, 0xdf, 0xfb, 0x8d, 0x05, 0x7b, 0x8f, 0xeb,
	0x1d, 0xeb, 0x41, 0xa2, 0x80, 0x9e, 0x42, 0x55, 0xd5, 0x27, 0xd3, 0x2e, 0x66, 0x6f, 0xc8, 0x6c,
	0x05, 0xe3, 0xaa, 0x1b, 0x81, 0x8d, 0x3f, 0xf2, 0xb0, 0xb6, 0xb8, 0x47, 0x2f, 0xa9, 0x3c, 0x56,
	0xc9, 0x43, 0x6a, 0xd1, 0x69, 0xa8, 0x92, 0xa8, 0x85, 0x82, 0xe2, 0x37, 0x7a, 0x9f, 0x81, 0xf8,
	0x60, 0x95, 0x75, 0x57, 0x76, 0x25, 0xc9, 0x06, 0x6e, 0x55, 0x1d, 0x9e, 0x19, 0x8a, 0xf2, 0xd7,
	0x5b, 0xcb, 0x49, 0x90, 0xa6, 0xe3, 0xb2, 0xd7, 0x42, 0x10, 0x01, 0xd8, 0x74, 0x84, 0x28, 0x20,
	0x06, 0x2f, 0x2d, 0x84, 0x43, 0x10, 0x23, 0xd0, 0x4b, 0x28, 0x77, 0xc8, 0xe1, 0x74, 0x6c, 0x46,
	0xd5, 0xf6, 0xf0, 0xb2, 0x21, 0xd4, 0x54, 0x78, 0x59, 0x3c, 0x65, 0x5b, 0x52, 0x8d, 0xaf, 0xa1,
	0x96, 0x16, 0x2c, 0x28, 0x9f, 0x3b, 0xe9, 0xf2, 0x39, 0x1f, 0x55, 0xaa, 0x9c, 0x7e, 0xcb, 0xc3,
	0xd2, 0xdc, 0x14, 0xe3, 0xd7, 0x7b, 0xcf, 0xf3, 0x48, 0xa0, 0x72, 0x27, 0xad, 0xea, 0x4e, 0xc2,
	0xe2, 0x17, 0xb7, 0x40, 0x44, 0x59, 0x94, 0xe9, 0xad, 0x39, 0x29, 0x5e, 0x72, 0x77, 0x15, 0xfe,
	0xc5, 0xdd, 0xc5, 0xde, 0x4e, 0x95, 0xd7, 0xe4, 0xd8, 0x19, 0x9d, 0x90, 0x50, 0x15, 0xc7, 0xea,
	0x5c, 0xeb, 0x2a, 0x21, 0xae, 0x9c, 0x2a, 0x14, 0xfa, 0x1c, 0x60, 0x8f, 0xd8, 0xec, 0x20, 0x02,
	0xc7, 0xf2, 0x58, 0xf2, 0x33, 0xdd, 0xcb, 0x74, 0x12, 0x31, 0x86, 0x49, 0xbc, 0x46, 0xdb, 0x50,
	0x1f, 0xf8, 0x5e, 0x9f, 0xbd, 0x3b, 0x83, 0xd8, 0xa5, 0x96, 0xad, 0x66, 0xa6, 0x9e, 0x01, 0xe1,
	0xba, 0x97, 0xd1, 0xba, 0xf7, 0x57, 0x2e, 0xf5, 0xc2, 0x44, 0xff, 0x63, 0x4f, 0x90, 0x41, 0xa7,
	0xfb, 0xf6, 0xa0, 0xd3, 0x7d, 0xd1, 0x7e, 0xb5, 0x63, 0xd6, 0xaf, 0xa0, 0xab, 0xec, 0x51, 0x2a,
	0x58, 0x5b, 0x6d, 0x7c, 0xb0, 0x89, 0xdb, 0x83, 0x4e, 0x3d, 0xc7, 0x66, 0xf3, 0x72, 0xc2, 0x34,
	0xf7, 0xf7, 0xba, 0xf5, 0xfc, 0x3c, 0x70, 0x6b, 0x77, 0x67, 0x17, 0xd7, 0x0b, 0x6c, 0x04, 0xd4,
	0x13, 0x66, 0xbf, 0x8d, 0xbf, 0xe9, 0xe2, 0x7a, 0x91, 0x15, 0xef, 0x6a, 0xc2, 0xdd, 0xdb, 0x69,
	0x9b, 0x5d, 0x69, 0xa4, 0x84, 0x36, 0xe0, 0x5a, 0x56, 0x22, 0x4d, 0x69, 0xec, 0xc0, 0x6e, 0xa6,
	0x44, 0xdd, 0x4e, 0x77, 0x68, 0xe2, 0x5e, 0x7b, 0x70, 0xd0, 0x36, 0x4d, 0x15, 0x43, 0x99, 0x8d,
	0x91, 0x5b, 0x12, 0x33, 0xd8, 0x1d, 0xf4, 0x77, 0xcd, 0x5d, 0xfc, 0xba, 0xbb, 0xdd, 0xdb, 0xda,
	0xe9, 0xa6, 0x40, 0x95, 0xd6, 0xaf, 0xf9, 0xf8, 0x7d, 0x33, 0x24, 0xc1, 0xa9, 0x33, 0x22, 0x68,
	0x93, 0xf7, 0x8c, 0x9a, 0xad, 0x68, 0xfd, 0xa2, 0x61, 0xd8, 0xd8, 0xb8, 0xb0, 0xd6, 0x8d, 0x2b,
	0xe8, 0x5b, 0x58, 0x56, 0xf7, 0x75, 0x64, 0xe8, 0xff, 0xe7, 0xe0, 0xe9, 0x37, 0x4d, 0xe3, 0xe6,
	0x45, 0xe2, 0xd8, 0xe4, 0x17, 0x50, 0x79, 0x49, 0xa8, 0x7c, 0x2c, 0xaf, 0x65, 0x9e, 0xfd, 0x91,
	0x95, 0xeb, 0xe7, 0xf8, 0xb1, 0xfa, 0x0b, 0xd0, 0x23, 0x75, 0xf6, 0x31, 0x80, 0x36, 0xb2, 0x1f,
	0x0e, 0xf1, 0x67, 0x46, 0xa3, 0xb1, 0x48, 0x14, 0xd9, 0x39, 0xd4, 0xc4, 0x17, 0xce, 0x93, 0xbf,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x66, 0xac, 0xc8, 0x18, 0x0d, 0x00, 0x00,
}
